<? $p = $this->pParametros(); ?>
<!DOCTYPE html>
<html>
  <head>
    <title>Devem Admin - Dvillagra</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <meta name="description" content="Devem Admin - Dvillagra" />

    <meta name="author" content="Dvillagra" />

    <link rel="shortcut icon" href="<?=Url::baseAdmin('view/img/favicon.ico')?>">

    <?php include('admin/include/scriptMenu.admin.php');?>

  </head>

  <body>
    <!-- Main Container start -->
    <div class="dashboard-container">

      <div class="container">

        <!-- Row Start -->
        <div class="row">
          <div class="col-lg-4 col-md-4 col-md-offset-4">
            
            <div class="page-not-found center-align-text">
              <div class="number">500</div>
              <h3>
                Erro interno do servidor.
              </h3>
              <p>
                Tente novamente mais tarde ou entre em contato com o administrador da aplicação
              </p>
            </div>

          </div>
        </div>
        <!-- Row End -->

      </div>
    </div>
    <!-- Main Container end -->

    <script src="<?=Url::baseAdmin('view/js/jquery.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/bootstrap.min.js')?>"></script>

  </body>
</html>