<? $p = $this->pParametros(); ?>
<!DOCTYPE html>
<html>
  <head>
    <title>Devem Admin - Dvillagra</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <meta name="description" content="Devem Admin - Dvillagra" />

    <meta name="author" content="Dvillagra" />

    <link rel="shortcut icon" href="<?=Url::baseAdmin('view/img/favicon.ico')?>">

    <?php include('admin/include/scriptMenu.admin.php');?>

  </head>

  <body>

    <!-- @HEADER -->
      <?php include('admin/include/header.admin.php');?>
    <!-- @END HEADER -->

        <!-- Sub Nav End -->
        <div class="sub-nav hidden-sm hidden-xs">
          <ul>
            <li><a href="" class="heading">Blog</a></li>
          </ul>
          <div class="custom-search hidden-sm hidden-xs">
            <input type="text" class="search-query" placeholder="Buscar ...">
            <i class="fa fa-search"></i>
          </div>
        </div>
        <!-- Sub Nav End -->

        <!-- Dashboard Wrapper Start -->
        <div class="dashboard-wrapper-lg">
          
          <!-- Blog Container Start -->
          <div class="blog-container">
            
            <h1 class="center-align-text">Know More About BlueMoon</h1>

            <!-- Row Start -->
            <div class="row">
              <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">

                <!-- Row Start -->
                <div class="row">
                  <div class="col-md-8">
                    
                    <!-- Blog One Starts -->
                    <div class="blog-wrapper">
                      <img src="img/bluemoon-blog7.jpg" class="blog-image img-responsive" alt="Bluemoon Blog">
                      <div class="blog-body">
                        <div class="blog-type">
                          <i class="fa fa-picture-o"></i>
                        </div>
                        <div class="date">
                          10, Apr 2015
                        </div>
                        <div class="blog-title">
                          It's Time to get to know your users.
                        </div>
                        <p class="blog-info">
                          This "trend chart" shows loading times across releases of a hypothetical web application. It is a mixture of a line chart and an area chart, with the daily median loading time indicated by the line and percentile ranges indicated by the surrounding areas. The "lollipops" mark releases of (different parts of) the application.
                        </p>
                        <a href="blog-full-page.html" class="blog-btn">Continue Reading</a>
                      </div>
                    </div>
                    <!-- Blog One Ends -->

                    <!-- Blog Starts -->
                    <div class="blog-wrapper">
                      <img src="img/bluemoon-blog5.jpg" class="blog-image img-responsive" alt="Bluemoon Blog">
                      <div class="blog-body">
                        <div class="blog-type">
                          <i class="fa fa-video-camera"></i>
                        </div>
                        <div class="date">
                          10, Apr 2015
                        </div>
                        <div class="blog-title">
                          It's Time to get to know your users.
                        </div>
                        <p class="blog-info">
                          This "trend chart" shows loading times across releases of a hypothetical web application. It is a mixture of a line chart and an area chart, with the daily median loading time indicated by the line and percentile ranges indicated by the surrounding areas. The "lollipops" mark releases of (different parts of) the application.
                        </p>
                        <a href="blog-full-page.html" class="blog-btn">Continue Reading</a>
                      </div>
                    </div>
                    <!-- Blog Ends -->

                    <!-- Blog Starts -->
                    <div class="blog-wrapper">
                      <img src="img/bluemoon-blog1.jpg" class="blog-image img-responsive" alt="Bluemoon Blog">
                      <div class="blog-body">
                        <div class="blog-type">
                          <i class="fa fa-file-o"></i>
                        </div>
                        <div class="date">
                          10, Apr 2015
                        </div>
                        <div class="blog-title">
                          It's Time to get to know your users.
                        </div>
                        <p class="blog-info">
                          This "trend chart" shows loading times across releases of a hypothetical web application. It is a mixture of a line chart and an area chart, with the daily median loading time indicated by the line and percentile ranges indicated by the surrounding areas. The "lollipops" mark releases of (different parts of) the application.
                        </p>
                        <a href="blog-full-page.html" class="blog-btn">Continue Reading</a>
                      </div>
                    </div>
                    <!-- Blog Ends -->

                  </div>
                  <div class="col-md-4">
                    
                    <!-- Blog Starts -->
                    <div class="blog-wrapper">
                      <img src="img/bluemoon-blog4.jpg" class="blog-image img-responsive" alt="Bluemoon Blog">
                      <div class="blog-body">
                        <div class="date">
                          10, Apr 2015
                        </div>
                        <div class="blog-title">
                          To know your users.
                        </div>
                        <p class="blog-info">
                          This "trend chart" shows loading times across releases of a hypothetical web application. It is a mixture of a line chart and an area chart, with the daily median loading time indicated by the line and percentile ranges indicated by the surrounding areas. The "lollipops" mark releases of (different parts of) the application.
                        </p>
                        <a href="blog-full-page.html" class="blog-btn">Continue Reading</a>
                      </div>
                    </div>
                    <!-- Blog Ends -->

                    <!-- Blog Starts -->
                    <div class="blog-wrapper">
                      <img src="img/bluemoon-blog3.jpg" class="blog-image img-responsive" alt="Bluemoon Blog">
                      <div class="blog-body">
                        <div class="date">
                          10, Apr 2015
                        </div>
                        <div class="blog-title">
                          It's Time to get to know your users.
                        </div>
                        <p class="blog-info">
                          This "trend chart" shows loading times across releases of a hypothetical web application. It is a mixture of a line chart and an area chart, with the daily median loading time indicated by the line and percentile ranges indicated by the surrounding areas. The "lollipops" mark releases of (different parts of) the application.
                        </p>
                        <a href="blog-full-page.html" class="blog-btn">Continue Reading</a>
                      </div>
                    </div>
                    <!-- Blog Ends -->

                    <!-- Blog Starts -->
                    <div class="blog-wrapper">
                      <img src="img/bluemoon-blog2.jpg" class="blog-image img-responsive" alt="Bluemoon Blog">
                      <div class="blog-body">
                        <div class="date">
                          10, Apr 2015
                        </div>
                        <div class="blog-title">
                          It's Time to get to know your users.
                        </div>
                        <p class="blog-info">
                          This "trend chart" shows loading times across releases of a hypothetical web application. It is a mixture of a line chart and an area chart, with the daily median loading time indicated by the line and percentile ranges indicated by the surrounding areas. The "lollipops" mark releases of (different parts of) the application.
                        </p>
                        <a href="blog-full-page.html" class="blog-btn">Continue Reading</a>
                      </div>
                    </div>
                    <!-- Blog Ends -->

                  </div>
                </div>
                <!-- Row Ends -->

              </div>
            </div>
            <!-- Row Ends -->

          </div>
          <!-- Blog Container End -->

        </div>
        <!-- Dashboard Wrapper End -->

        <!-- @FOOTER -->
        <?php include('admin/include/footer.admin.php');?>
      <!-- @END FOOTER -->

      </div>
    </div>
    <!-- Main Container end -->

    <script src="<?=Url::baseAdmin('view/js/jquery.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/bootstrap.min.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/jquery.scrollUp.js')?>"></script>
    
    <!-- Custom JS -->
    <script src="<?=Url::baseAdmin('view/js/menu.js')?>"></script>
    
    <script type="text/javascript">
      //ScrollUp
      $(function () {
        $.scrollUp({
          scrollName: 'scrollUp', // Element ID
          topDistance: '300', // Distance from top before showing element (px)
          topSpeed: 300, // Speed back to top (ms)
          animation: 'fade', // Fade, slide, none
          animationInSpeed: 400, // Animation in speed (ms)
          animationOutSpeed: 400, // Animation out speed (ms)
          scrollText: 'Top', // Text for element
          activeOverlay: false, // Set CSS color to display scrollUp active point, e.g '#00FFFF'
        });
      });

      //Tooltip
      $('a').tooltip('hide');
      $('i').tooltip('hide');

    </script>

  </body>
</html>