<? $p = $this->pParametros(); ?>

<!DOCTYPE html>
<html>
  <head>

      <meta charset="utf-8">

      <?php include('core/include.tags.core.php');?>

      <?php require_once('core/include.scripts.core.php');?>

      <link rel="stylesheet" href="<?=Url::base('core/js/vendor/datatables/css/dataTables.bootstrap.css')?>" type="text/css" />
      <link rel="stylesheet" href="<?=Url::base('core/js/vendor/datatables/css/ColVis.css')?>" type="text/css" />
      <link rel="stylesheet" href="<?=Url::base('core/js/vendor/datatables/css/TableTools.css')?>" type="text/css" />

      <script  src="<?=Configuracoes::CheckFileCustomer('js/Cliente.class.js', true)?>" ></script>
    
  </head>

<body class="bg-1">

    <!-- Preloader -->
    <div class="mask"><div id="loader"></div></div>
    <!--/Preloader -->

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Make page fluid -->
      <div class="row">
        
        <!-- @HEADER -->
          <?php include('core/include.header.core.php');?>
        <!-- @END HEADER -->
        
        <!-- Page content -->
        <div id="content" class="col-md-12">
          
          <!-- page header -->
          <div class="pageheader">
          
            <h2><i class="fa fa-users" style="line-height: 48px;padding-left: 0;"></i> Clientes</h2>
            
            <div class="breadcrumbs">

              <ol class="breadcrumb">

                <li>Você está em</li>
                <li><a>Clientes</a></li>

              </ol>

            </div>

          </div>
          <!-- /page header -->
          
          <!-- content main container -->
          <div class="main">

            <!-- row -->
            <div class="row">

              <div class="col-md-12">

                <section class="tile color transparent-black">

                  <!-- tile header -->
                  <div class="tile-header">

                    <h1>Cadastro de novo Cliente </h1>

                    <div class="controls">

                      <a class="minimize" href="#"><i class="fa fa-chevron-down"></i></a>
                      <!--a class="refresh" href="#"><i class="fa fa-refresh"></i></a>
                      <a class="remove" href="#"><i class="fa fa-times"></i></a-->

                    </div>

                  </div>
                  <!-- /tile header -->

                  <!-- tile body -->
                  <div class="tile-body">

                    <form id="form_cadastro">
                    
                      <div class="row">

                        <div class="form-group col-sm-2">

                          <label for="exampleInputEmail">Usuário</label>
                          <input type="text" placeholder="Nome de usuário" id="cd_nickname" name="cd_nickname" class="form-control form-devem-rec">

                        </div>

                        <div class="form-group col-sm-3">

                          <label for="exampleInputPassword1">Primeiro Nome</label>
                          <input type="text" placeholder="Nome" id="cd_nome" name="cd_nome" class="form-control form-devem-rec">
                        
                        </div>
                        <div class="form-group col-sm-3">

                          <label for="exampleInputPassword2">Sobrenome</label>
                          <input type="text" placeholder="Sobrenome" id="cd_sobrenome" name="cd_sobrenome" class="form-control form-devem-rec">
                        
                        </div>
                        <div class="form-group col-sm-2">

                          <label for="exampleInputPassword2">CPF</label>
                          <input type="text" placeholder="CPF" id="cd_cpf" name="cd_cpf" class="form-control form-devem-rec">
                        
                        </div>
                        <div class="form-group col-sm-2">

                          <label for="exampleInputPassword2">Tipo</label>
                          <input type="text" placeholder="Tipo de pessoa" id="cd_tipo" name="cd_tipo" class="form-control form-devem-rec">
                        
                        </div>

                      </div>

                      <div class="row">

                        <div class="form-group col-sm-1">

                          <label for="exampleInputCity">CEP</label>
                          <input type="text" placeholder="CEP" id="cd_cep" name="cd_cep" class="form-control form-devem-rec">
                        
                        </div>

                        <div class="form-group col-sm-3">
                          
                          <label for="exampleInputAddress">Endereço</label>
                          <input type="text" placeholder="Endereço" id="cd_endereco" name="cd_endereco" class="form-control form-devem-rec">
                        
                        </div>

                        <div class="form-group col-sm-1">
                          
                          <label for="exampleInputCity">Nº</label>
                          <input type="text" id="cd_numero" name="cd_numero" placeholder="Número" class="form-control form-devem-rec">
                        
                        </div>

                        <div class="form-group col-sm-2">
                          
                          <label for="exampleInputCity">Bairro</label>
                          <input type="text" id="cd_bairro" name="cd_bairro" placeholder="Bairro" class="form-control">
                        
                        </div>

                        <div class="form-group col-sm-2">
                          
                          <label for="exampleInputCity">Complemento</label>
                          <input type="text" id="cd_complemento" name="cd_complemento" placeholder="Complemento" class="form-control">
                        
                        </div>

                        <div class="form-group col-sm-2">
                        
                          <label for="exampleInputCity">Cidade</label>
                          <input type="text" id="cd_cidade" name="cd_cidade" placeholder="Cidade" class="form-control form-devem-rec">
                        
                        </div>

                        <div class="form-group col-sm-1">
                        
                          <label for="exampleInputCity">UF</label>
                          <input type="text" id="cd_estado" name="cd_estado" placeholder="Estado" class="form-control form-devem-rec">
                        
                        </div>

                      </div>

                      <div class="row">

                        <div class="form-group col-sm-2">
                        
                          <label for="exampleInputCity">Telefone</label>
                          <input type="text" id="cd_telefone" name="cd_telefone" placeholder="Telefone" class="form-control">
                        
                        </div>

                        <div class="form-group col-sm-2">
                        
                          <label for="exampleInputAddress">Celular</label>
                          <input type="text" id="cd_celular" name="cd_celular" placeholder="Celular" class="form-control">
                        
                        </div>

                        <div class="form-group col-sm-4">
                        
                          <label for="exampleInputCity">E-mail</label>
                          <input type="text" id="cd_email" name="cd_email" placeholder="E-mail" class="form-control form-devem-rec">
                        
                        </div>

                        <div class="form-group col-sm-4">
                        
                          <label for="exampleInputCity">Confirma E-mail</label>
                          <input type="text" id="cd_email_conf" name="cd_email_conf" placeholder="Confirmar E-mail" class="form-control form-devem-rec">
                       
                        </div>

                      </div>
                    </form>

                    <section class="log-in">
                     
                      <button class="btn btn-greensea" id="bt_cadastrar" >Cadastrar</button>
                      <button class="btn btn-slategray" id="bt_retorna">Cancelar</button>
                    
                    </section>

                  </div>
                  <!-- /tile body -->
                
                </section>
                
                <!-- /tile -->

                <!-- tile -->
                <section class="tile transparent">

                  <!-- tile header -->
                  <div class="tile-header transparent">
                    
                    <h1>Listagem dos seus Clientes </h1>
                    <span class="note">* <span class="italic">apenas ativados</span></span>
                    
                    <div class="controls">
                    
                      <a href="#" class="minimize"><i class="fa fa-chevron-down"></i></a>
                      <!--a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                      <a href="#" class="remove"><i class="fa fa-times"></i></a-->
                    
                    </div>
                  
                  </div>
                  <!-- /tile header -->

                  <!-- tile body -->
                  <div class="tile-body rounded-corners">
                    
                    <div class="table-responsive">
                      
                      <table  class="table table-datatable table-custom" id="drillDownDataTable">

                        <thead>
                          <tr>
                            <th class="no-sort" style="width: 45px"></th>
                            <th class="sort-alpha">ID</th>
                            <th class="sort-alpha">NOME</th>
                            <th class="sort-alpha">RANKING</th>
                            <th class="sort-alpha">REPUTACAO</th>
                            <th class="sort-alpha">DESEMPENHO (%)</th>
                            <th class="sort-alpha">DATA REGISTRO</th>
                          </tr>
                        </thead>

                        <tbody>
                        </tbody>
                      
                      </table>
                    
                    </div>

                  </div>
                  <!-- /tile body -->
                
                </section>
                <!-- /tile -->
              </div>

            </div>
            <!-- /row -->
          
          </div>
          <!-- /content container -->

        </div>
        <!-- Page content end -->

      </div>
      <!-- Make page fluid-->

    </div>
    <!-- Wrap all page content end -->

    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js?lang=css&amp;skin=sons-of-obsidian"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/jquery.dataTables.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/ColReorderWithResize.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/colvis/dataTables.colVis.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/tabletools/ZeroClipboard.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/tabletools/dataTables.tableTools.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/dataTables.bootstrap.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap-dropdown-multilevel.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/mmenu/js/jquery.mmenu.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/sparkline/jquery.sparkline.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/nicescroll/jquery.nicescroll.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/animate-numbers/jquery.animateNumbers.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/blockui/jquery.blockUI.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/morris/morris.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/tabdrop/bootstrap-tabdrop.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/summernote/summernote.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/chosen/chosen.jquery.min.js')?>"></script>
    <script src="<?=Url::base('core/js/devem/minimal.min.js')?>"></script>

  </body>
  
</html>
      