<? $p = $this->pParametros(); ?>
<!DOCTYPE html>
<html>
  <head>
    <title>Devem Admin - Dvillagra</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <meta name="description" content="Devem Admin - Dvillagra" />

    <meta name="author" content="Dvillagra" />

    <link rel="shortcut icon" href="<?=Url::baseAdmin('view/img/favicon.ico')?>">

    <?php include('admin/include/scriptMenu.admin.php');?>

  </head>

  <body>

    <!-- @HEADER -->
      <?php include('admin/include/header.admin.php');?>
    <!-- @END HEADER -->

        <!-- Sub Nav End -->
        <div class="sub-nav hidden-sm hidden-xs">
          <ul>
            <li><a href="" class="heading">Formulários</a></li>
            <li class="hidden-sm hidden-xs">
              <a href="#color-picker">Color Picker</a>
            </li>
            <li class="hidden-sm hidden-xs">
              <a href="#create-account">Criar conta</a>
            </li>
            <li class="hidden-sm hidden-xs">
              <a href="#inputs">Inputs</a>
            </li>
          </ul>
          <div class="custom-search hidden-sm hidden-xs">
            <input type="text" class="search-query" placeholder="Buscar ...">
            <i class="fa fa-search"></i>
          </div>
        </div>
        <!-- Sub Nav End -->

        <!-- Dashboard Wrapper Start -->
        <div class="dashboard-wrapper">
          
          <!-- Left Sidebar Start -->
          <div class="left-sidebar">
            
            <!-- Row Start -->
            <div class="row">
              <div class="col-lg-12 col-md-12">
                <div class="widget">
                  <div class="widget-header">
                    <div class="title">
                      Bootstrap-wysihtml5 
                      <span class="mini-title">
                        Editor simples
                      </span>
                    </div>
                    <span class="tools">
                      <i class="fa fa-cogs"></i>
                    </span>
                  </div>
                  <div class="widget-body">
                    <div class="hero-unit">
                      <textarea class="textarea form-control" placeholder="Digite ..."></textarea>
                    </div>
                    <button class="btn btn-primary btn-lg" type="button"><i class="icon-envelope"></i> Salvar alterações</button>
                    <button class="btn btn-default btn-lg" type="button">Cancelar</button>
                  </div>
                </div>
              </div>
            </div>
            <!-- Row End -->

            <!-- Row Start -->
            <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="widget">
                  <div class="widget-header">
                    <div class="title">
                      Color picke <a id="color-picker">r</a>
                    </div>
                    <span class="tools">
                      <i class="fa fa-cogs"></i>
                    </span>
                  </div>
                  <div class="widget-body">
                    <div class="row">
                      <div class="col-lg-3 col-md-3 col-sm-6 col-sx-12">
                        <div class="form-group">
                          <label for="hue-demo">Hue (default)</label>
                          <input type="text" id="hue-demo" class="form-control demo" data-control="hue" value="#ff6161">
                        </div>
                      </div>
                      <div class="col-lg-3 col-md-3 col-sm-6 col-sx-12">
                        <div class="form-group">
                          <label for="saturation-demo">Saturação</label>
                          <input type="text" id="saturation-demo" class="form-control demo" data-control="saturation" value="#0088cc">
                        </div>
                      </div>
                      <div class="col-lg-3 col-md-3 col-sm-6 col-sx-12">
                        <div class="form-group">
                          <label for="brightness-demo">Brilho</label>
                          <input type="text" id="brightness-demo" class="form-control demo" data-control="brightness" value="#00ffff">
                        </div>
                      </div>
                      <div class="col-lg-3 col-md-3 col-sm-6 col-sx-12">
                        <div class="form-group">
                          <label for="wheel-demo">Wheel</label>
                          <input type="text" id="wheel-demo" class="form-control demo" data-control="wheel" value="#ff99ee">
                        </div>
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-lg-4 col-md-4 col-sm-4 col-sx-12">
                        <div class="form-group">
                          <label for="opacity">Transparência</label>
                          <br>
                          <input type="text" id="opacity" class="form-control demo" data-opacity=".5" value="#766fa8">
                          <span class="help-block">
                            Permite adicionar transparencia no input
                          </span>
                        </div>
                      </div>
                      <div class="col-lg-4 col-md-4 col-sm-4 col-sx-12">
                        <div class="form-group">
                          <label for="default-value">Valor Default</label>
                          <br>
                          <input type="text" id="default-value" class="form-control demo" data-defaultValue="#ff6600">
                          <span class="help-block">
                            Esse campo é apara o valor default
                          </span>
                        </div>
                      </div>
                      <div class="col-lg-4 col-md-4 col-sm-4 col-sx-12">
                        <div class="form-group">
                          <label for="letter-case">Letra</label>
                          <br>
                          <input type="text" id="letter-case" class="form-control demo" data-letterCase="uppercase" value="#abcdef">
                          <span class="help-block">
                            Nesse campo somente caixa alta
                          </span>
                        </div>
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-lg-3 col-md-3 col-sm-6 col-sx-12">
                        <div class="form-group">
                          <label for="position-bottom-left">Bottom left (default)</label>
                          <input type="text" id="position-bottom-left" class="form-control demo" data-position="bottom left" value="#0088cc">
                        </div>
                      </div>
                      <div class="col-lg-3 col-md-3 col-sm-6 col-sx-12">
                        <div class="form-group">
                          <label for="position-top-left">Top left</label>
                          <input type="text" id="position-top-left" class="form-control demo" data-position="top left" value="#0088cc">
                        </div>
                      </div>
                      <div class="col-lg-3 col-md-3 col-sm-6 col-sx-12">
                        <div class="form-group">
                          <label for="position-bottom-right">Bottom right</label>
                          <input type="text" id="position-bottom-right" class="form-control demo" data-position="bottom right" value="#0088cc">
                        </div>
                      </div>
                      <div class="col-lg-3 col-md-3 col-sm-6 col-sx-12">
                        <div class="form-group">
                          <label for="position-top-right">Top right</label>
                          <input type="text" id="position-top-right" class="form-control demo" data-position="top right" value="#0088cc">
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- Row End -->

            <!-- Row Start -->
            <div class="row">
              <div class="col-lg-12 col-md-12">
                <div class="widget">
                  <div class="widget-header">
                    <div class="title">
                      Criar conta
                      <span class="mini-title">
                        Formulário simples para criar conta <a id="create-account">t</a>
                      </span>
                    </div>
                  </div>
                  <div class="widget-body">
                    <form class="form-horizontal no-margin">
                      <div class="form-group">
                        <label for="userName" class="col-sm-2 control-label">Nome</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control" id="userName" placeholder="Nome">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="emailId" class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-10">
                          <input type="email" class="form-control" id="emailId" placeholder="Email">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="pwd" class="col-sm-2 control-label">Senha</label>
                        <div class="col-sm-10">
                          <input type="password" class="form-control" id="pwd" placeholder="Senha">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="rptPwd" class="col-sm-2 control-label">Repita a senha</label>
                        <div class="col-sm-10">
                          <input type="password" class="form-control" id="rptPwd" placeholder="Senha">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="pwd" class="col-sm-2 control-label">Nascimento</label>
                        <div class="col-sm-10">
                          <div class="row">
                            <div class="col-md-4 col-sm-4 col-xs-4">
                              <select id="DateOfBirthMonth" class="form-control">
                                <option>
                                  - Mês -
                                </option>
                                <option value="1">
                                  Janeiro
                                </option>
                                <option value="2">
                                  Fevereiro
                                </option>
                                <option value="3">
                                  Março
                                </option>
                                <option value="4">
                                  Abril
                                </option>
                                <option value="5">
                                  Maio
                                </option>
                                <option value="6">
                                  Junho
                                </option>
                              </select>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4">
                              <select name="DateOfBirth_Day"  class="form-control">
                                <option>
                                  - Dia -
                                </option>
                                <option value="1">
                                  1
                                </option>
                                <option value="2">
                                  2
                                </option>
                                <option value="3">
                                  3
                                </option>
                                <option value="4">
                                  4
                                </option>
                                <option value="5">
                                  5
                                </option>
                                <option value="6">
                                  6
                                </option>
                                <option value="7">
                                  7
                                </option>
                                <option value="8">
                                  8
                                </option>
                                <option value="9">
                                  9
                                </option>
                                <option value="10">
                                  10
                                </option>
                              </select>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4">
                              <select name="DateOfBirth_Year" class="form-control">
                                <option>
                                  - Ano -
                                </option>
                                <option value="2013">
                                  2013
                                </option>
                                <option value="2012">
                                  2012
                                </option>
                                <option value="2011">
                                  2011
                                </option>
                                <option value="2010">
                                  2010
                                </option>
                                <option value="2009">
                                  2009
                                </option>
                                <option value="2008">
                                  2008
                                </option>
                                <option value="2007">
                                  2007
                                </option>
                                <option value="2006">
                                  2006
                                </option>
                                <option value="2005">
                                  2005
                                </option>
                              </select>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="country" class="col-sm-2 control-label">País</label>
                        <div class="col-sm-10">
                          <select id="country" class="form-control">
                            <option value="">
                              País...
                            </option>
                            <option value="Afganistan">
                              Afghanistan
                            </option>
                            <option value="Albania">
                              Albania
                            </option>
                            <option value="Australia">
                              Australia
                            </option>
                            <option value="Austria">
                              Austria
                            </option>
                            <option value="Chile">
                              Chile
                            </option>
                            <option value="China">
                              China
                            </option>
                            <option value="India">
                              India
                            </option>
                            <option value="Indonesia">
                              Indonesia
                            </option>
                            <option value="Korea Sout">
                              Korea South
                            </option>
                            <option value="Kuwait">
                              Kuwait
                            </option>
                            <option value="Macau">
                              Macau
                            </option>
                            <option value="Malaysia">
                              Malaysia
                            </option>
                            <option value="Malawi">
                              Malawi
                            </option>
                            <option value="Maldives">
                              Maldives
                            </option>
                            <option value="Mali">
                              Mali
                            </option>
                            <option value="Malta">
                              Malta
                            </option>
                            <option value="Mayotte">
                              Mayotte
                            </option>
                            <option value="Zaire">
                              Zaire
                            </option>
                            <option value="Zambia">
                              Zambia
                            </option>
                            <option value="Zimbabwe">
                              Zimbabwe
                            </option>
                          </select>
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <div class="checkbox">
                            <label>
                              <input type="checkbox"> Sim, eu quero receber e-mails com promoções.
                            </label>
                          </div>
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <div class="checkbox">
                            <label>
                              <input type="checkbox"> Lembrar-me :).
                            </label>
                          </div>
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-info">Criar Conta</button>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <!-- Row End -->

            <!-- Row Start -->
            <div class="row">
              <div class="col-lg-12 col-md-12">
                <div class="widget">
                  <div class="widget-header">
                    <div class="title">
                      Input <a id="inputs">s</a>
                    </div>
                    <span class="tools">
                      <i class="fa fa-cogs"></i>
                    </span>
                  </div>
                  <div class="widget-body">
                    <form class="form-horizontal row-border" action="#">
                      <div class="form-group">
                        <label class="col-md-2 control-label">Input Default</label>
                        <div class="col-md-10">
                          <input type="text" name="regular" class="form-control">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-md-2 control-label">Senha</label>
                        <div class="col-md-10">
                          <input class="form-control" type="password" name="pass">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-md-2 control-label">Placeholder</label>
                        <div class="col-md-10">
                          <input class="form-control" type="text" name="placeholder" placeholder="placeholder">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-md-2 control-label">Desabilitado</label>
                        <div class="col-md-10">
                          <input type="text" name="disabled" disabled="disabled" value="disabled" class="form-control">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-md-2 control-label">Somente Leitura</label>
                        <div class="col-md-10">
                          <input class="form-control" type="text" name="readonly" readonly="" value="Somente Leitura">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-md-2 control-label">Texto de Ajuda</label>
                        <div class="col-md-10">
                          <input type="text" name="regular" class="form-control">
                          <span class="help-block">Lorem e lorem e blablabla.</span>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-md-2 control-label">Predefinir</label>
                        <div class="col-md-10">
                          <input type="text" name="regular" value="http://" class="form-control">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-md-2 control-label">Com Icone</label>
                        <div class="col-md-10">
                          <input type="text" name="regular" class="form-control">
                          <i class="icon-pencil input-icon"></i>
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="labelfor" class="col-md-2 control-label">Label clicável</label>
                        <div class="col-md-10">
                          <input type="text" name="labelfor" id="labelfor" class="form-control">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="col-md-2 control-label">Tamanho de coluna</label>
                        <div class="col-md-10">
                          <div class="row">
                            <div class="col-xs-3">
                              <input type="text" class="form-control" placeholder=".col-xs-3">
                            </div>
                            <div class="col-xs-5">
                              <input type="text" class="form-control" placeholder=".col-xs-5">
                            </div>
                            <div class="col-xs-4">
                              <input type="text" class="form-control" placeholder=".col-xs-4">
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="form-group has-success">
                        <label class="col-md-2 control-label">Input com sucesso</label>
                        <div class="col-md-10">
                          <input type="text" class="form-control" id="inputSuccess" placeholder="Input com sucesso">
                          <i class="icon-pencil input-icon success"></i>
                        </div>
                      </div>
                      <div class="form-group has-warning">
                        <label class="col-md-2 control-label">Input com alerta</label>
                        <div class="col-md-10">
                          <input type="text" class="form-control" id="inputWarning" placeholder="Input com alerta">
                          <i class="icon-pencil input-icon warning"></i>
                        </div>
                      </div>
                      <div class="form-group has-error">
                        <label class="col-md-2 control-label">Input com erro</label>
                        <div class="col-md-10">
                          <input type="text" class="form-control" id="inputError" placeholder="Input com erro">
                          <i class="icon-pencil input-icon error"></i>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <!-- Row End -->

          </div>
          <!-- Left Sidebar End -->

          <!-- Right Sidebar Start -->
          <div class="right-sidebar">
            <div class="wrapper">
              <button class="btn btn-block btn-info" type="button">
                Bloco de botão de nível
              </button>
            </div>
            <div class="wrapper">
              <button class="btn btn-block btn-success" type="button">
                Bloco de botão de nível
              </button>
            </div>
            <div class="wrapper">
              <button class="btn btn-block btn-warning" type="button">
                Bloco de botão de nível
              </button>
            </div>
            
            <hr class="hr-stylish-1">
            
            <div class="wrapper">
              <ul class="progress-stats">
                <li>
                  <div class="details">
                    <span>Windows</span>
                    <span class="pull-right">78%</span>
                  </div>
                  <div class="progress progress-sm">
                    <div class="progress-bar" role="progressbar" aria-valuenow="78" aria-valuemin="0" aria-valuemax="100" style="width: 78%">
                    </div>
                  </div>
                </li>
                <li>
                  <div class="details">
                    <span>Windows 8</span>
                    <span class="pull-right">32%</span>
                  </div>
                  <div class="progress progress-sm">
                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="32" aria-valuemin="0" aria-valuemax="100" style="width: 32%">
                    </div>
                  </div>
                </li>
                <li>
                  <div class="details">
                    <span>Mac</span>
                    <span class="pull-right">84%</span>
                  </div>
                  <div class="progress progress-sm">
                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="84" aria-valuemin="0" aria-valuemax="100" style="width: 84%">
                    </div>
                  </div>
                </li>
                <li>
                  <div class="details">
                    <span>Linux</span>
                    <span class="pull-right">44%</span>
                  </div>
                  <div class="progress progress-sm">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="44" aria-valuemin="0" aria-valuemax="100" style="width: 44%">
                    </div>
                  </div>
                </li>
                <li>
                  <div class="details">
                    <span>IPhone/IPad</span>
                    <span class="pull-right">67%</span>
                  </div>
                  <div class="progress progress-sm">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="67" aria-valuemin="0" aria-valuemax="100" style="width: 67%">
                    </div>
                  </div>
                </li>
              </ul>
            </div>
            
            <hr class="hr-stylish-1">
            
            <div class="wrapper">
              <div class="btn-toolbar no-margin">
                <div class="btn-group">
                  <a href="#" class="btn btn-success">
                    <i class="fa fa-headphones"></i>
                  </a>
                  <a href="#" class="btn btn-warning">
                    <i class="fa fa-thumbs-down"></i>
                  </a>
                  <a href="#" class="btn btn-danger">
                    <i class="fa fa-tasks"></i>
                  </a>
                  <a href="#" class="btn btn-info">
                    <i class="fa fa-thumbs-up"></i>
                  </a>
                </div>
                <div class="btn-group">
                  <a href="#" class="btn btn-default">
                    <i class="fa fa-trash-o"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
          <!-- Right Sidebar End -->
        </div>
        <!-- Dashboard Wrapper End -->

        <!-- @FOOTER -->
        <?php include('admin/include/footer.admin.php');?>
      <!-- @END FOOTER -->

      </div>
    </div>
    <!-- Main Container end -->

    <script src="<?=Url::baseAdmin('view/js/wysi/wysihtml5-0.3.0.min.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/jquery.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/bootstrap.min.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/wysi/bootstrap3-wysihtml5.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/jquery.scrollUp.js')?>"></script>
    
    <!-- Color Picker -->
    <script src="<?=Url::baseAdmin('view/js/color-picker/jquery.minicolors.js')?>"></script>

    <!-- Custom JS -->
    <script src="<?=Url::baseAdmin('view/js/menu.js')?>"></script>
    
    <script type="text/javascript">
      //ScrollUp
      $(function () {
        $.scrollUp({
          scrollName: 'scrollUp', // Element ID
          topDistance: '300', // Distance from top before showing element (px)
          topSpeed: 300, // Speed back to top (ms)
          animation: 'fade', // Fade, slide, none
          animationInSpeed: 400, // Animation in speed (ms)
          animationOutSpeed: 400, // Animation out speed (ms)
          scrollText: 'Top', // Text for element
          activeOverlay: false, // Set CSS color to display scrollUp active point, e.g '#00FFFF'
        });
      });

      //Tooltip
      $('a').tooltip('hide');

      //Popover
      $('.popover-pop').popover('hide');

      //Dropdown
      $('.dropdown-toggle').dropdown();

      //wysihtml5
      $('.textarea').wysihtml5();

      //Color Pickers
      $(document).ready( function() {
      
        $('.demo').each( function() {
          $(this).minicolors({
            control: $(this).attr('data-control') || 'hue',
            defaultValue: $(this).attr('data-defaultValue') || '',
            inline: $(this).attr('data-inline') === 'true',
            letterCase: $(this).attr('data-letterCase') || 'lowercase',
            opacity: $(this).attr('data-opacity'),
            position: $(this).attr('data-position') || 'bottom left',
            change: function(hex, opacity) {
              if( !hex ) return;
              if( opacity ) hex += ', ' + opacity;
              try {
                console.log(hex);
              } catch(e) {}
            },
            theme: 'bootstrap'
          });
                
        });
      
      });

    </script>

  </body>
</html>