<? 

  $p = $this->pParametros(); 

  $uud = $p['uud'];
  $uudTotal = $p['uudTotal'];

  $pvd = $p['pvd'];
  $pvdTotal = $p['pvdTotal'];

  $cld = $p['cld'];
  $cldTotal = $p['cldTotal'];

  $pud = $p['pud'];
  $pudTotal = $p['pudTotal'];

?>
<!DOCTYPE html>
<html>
  <head>

      <meta charset="utf-8">

      <?php include('core/include.tags.core.php');?>

      <?php require_once('admin/include/include.scripts.admin.php');?>
    
  </head>

<body class="bg-1">

    <!-- Preloader -->
    <div class="mask"><div id="loader"></div></div>
    <!--/Preloader -->

    

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Make page fluid -->
      <div class="row">
        
        <!-- @HEADER -->
          <?php include('admin/include/include.header.admin.php');?>
        <!-- @END HEADER -->        
        
        <!-- Page content -->
        <div id="content" class="col-md-12">
          
          <!-- page header -->
          <div class="pageheader">
            
            <h2><i class="fa fa-tachometer"></i> Dashboard</h2>
            
            <div class="breadcrumbs">

              <ol class="breadcrumb">

                <li>Você está em </li>
                <li class="active">Dashboard</li>

              </ol>

            </div>

          </div>
          <!-- /page header -->
          
          <!-- content main container -->
          <div class="main">

            <!-- cards -->
            <div class="row cards">

              <div class="card-container col-lg-3 col-sm-6 col-xs-12">

                <div class="card card-slategray hover">

                  <div class="front"> 

                    <div class="media">    

                      <span class="pull-left">
                        <i class="fa fa-user media-object"></i>
                      </span>

                      <div class="media-body">
                        <small>Usuários Unicos Dia</small>
                        <h2 class="media-heading animate-number" data-value="<?=$uud?>" data-animation-duration="1500">0</h2>
                      </div>

                    </div> 

                    <div class="progress-list">

                      <div class="details">
                        <div class="title">Total</div>
                      </div>

                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="<?=$uudTotal?>" data-animation-duration="1500">0</span>
                      </div>

                    </div>

                  </div>

                  <div class="back">

                    <a href="<?=Url::base('rendimento/ranking')?>">
                      <i class="fa fa fa-signal fa-4x"></i>
                      <span>Veja o Ranking</span>
                    </a>

                  </div>

                </div>

              </div>
              
              <div class="card-container col-lg-3 col-sm-6 col-sm-12">

                <div class="card card-redbrown hover">

                  <div class="front"> 

                    <div class="media"> 

                      <span class="pull-left">
                        <i class="fa fa-file media-object"></i>
                      </span>

                      <div class="media-body">
                        <small>Page View Dia</small>
                        <h2 class="media-heading animate-number" data-value="<?=$pvd?>" data-animation-duration="1500">0</h2>
                      </div>

                    </div> 

                    <div class="progress-list">

                      <div class="details">
                        <div class="title">Total</div>
                      </div>

                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="<?=$pvdTotal?>" data-animation-duration="1500">0</span>
                      </div>

                    </div>


                  </div>

                  <div class="back">

                    <a href="<?=Url::base('cliente/cadastro')?>">
                      <i class="fa fa-file-text-o fa-4x"></i>
                      <span>Cadastrar Cliente</span>
                    </a>  

                  </div>

                </div>

              </div>

              <div class="card-container col-lg-3 col-sm-6 col-sm-12">

                <div class="card card-greensea hover">

                  <div class="front">        
                    
                    <div class="media">

                      <span class="pull-left">
                        <i class="fa fa-mouse-pointer media-object"></i>
                      </span>

                      <div class="media-body">
                        <small>Cliques Dia</small>
                        <h2 class="media-heading animate-number" data-value="<?=$cld?>" data-animation-duration="1500">0</h2>
                      </div>

                    </div>

                    <div class="progress-list">

                      <div class="details">
                        <div class="title">Total</div>
                      </div>

                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="<?=$cldTotal?>" data-animation-duration="1500">0</span>
                      </div>

                    </div>

                  </div>

                  <div class="back">

                    <a href="<?=Url::base('relatorio/ganho')?>">
                      <i class="fa fa-bar-chart-o fa-4x"></i>
                      <span>Veja os indicativos</span>
                    </a>

                  </div>

                </div>

              </div>

              <div class="card-container col-lg-3 col-sm-6 col-sm-12">

                <div class="card card-blue hover">

                  <div class="front">        
                    
                    <div class="media">   

                      <span class="pull-left">
                        <i class="fa fa-usd media-object"></i>
                      </span>

                      <div class="media-body">
                        <small>Publicidades Clicadas Dia</small>
                        <h2 class="media-heading animate-number" data-value="<?=$pud?>" data-animation-duration="1500">0</h2>
                      </div>

                    </div> 

                    <div class="progress-list">

                      <div class="details">
                        <div class="title">Total</div>
                      </div>

                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="<?=$pudTotal?>" data-animation-duration="1500">0</span>
                      </div>

                    </div>

                  </div>

                  <div class="back">

                    <a href="http://www.aguarochabranca.com.br" target="_blank">
                      <i class="fa fa-money fa-4x"></i>
                      <span>Ir para a loja</span>
                    </a>

                  </div>

                </div>

              </div>

            </div>
            <!-- /cards -->

          </div>
          <!-- /content container -->

        </div>
        <!-- Page content end -->

      </div>
      <!-- Make page fluid-->

    </div>
    <!-- Wrap all page content end -->

    <!-- Include all compiled plugins (below), or include individual files as needed -->

    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap-dropdown-multilevel.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/mmenu/js/jquery.mmenu.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/sparkline/jquery.sparkline.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/nicescroll/jquery.nicescroll.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/animate-numbers/jquery.animateNumbers.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/blockui/jquery.blockUI.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/easypiechart/jquery.easypiechart.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/rickshaw/raphael-min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/rickshaw/d3.v2.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/rickshaw/rickshaw.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/morris/morris.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/tabdrop/bootstrap-tabdrop.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/summernote/summernote.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/chosen/chosen.jquery.min.js')?>"></script>
    <script src="<?=Url::base('core/js/devem/minimal.min.js')?>"></script>

    <script>
    $(function(){

      // Initialize card flip
      $('.card.hover').hover(function(){
        $(this).addClass('flip');
      },function(){
        $(this).removeClass('flip');
      });

      //generate actual pie charts
      $('.pie-chart').easyPieChart();

      // sortable table
      $('.table.table-sortable th.sortable').click(function() {
        var o = $(this).hasClass('sort-asc') ? 'sort-desc' : 'sort-asc';
        $('th.sortable').removeClass('sort-asc').removeClass('sort-desc');
        $(this).addClass(o);
      });

      // Initialize tabDrop
      $('.tabdrop').tabdrop({text: '<i class="fa fa-th-list"></i>'});

      //load wysiwyg editor
      $('#msg-box').summernote({
        toolbar: false,
        height: 161   //set editable area's height
      });

      
      
    })
      
    </script>
  </body>
</html>
