<!DOCTYPE html>
<html>
  <head>

    <title>Devem - Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8" />

    <link rel="icon" type="image/ico" href="<?=Url::imgApp('icone/favicon.ico')?>" />

    <?php require_once('core/include.scripts-adm.core.php');?>

  </head>
  <body class="bg-1">

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Make page fluid -->
      <div class="row">

        <!-- Page content -->
        <div id="content" class="col-md-12 full-page login">

          <div class="inside-block">

            <img src="<?=Url::imgApp('icone_git.png')?>" alt class="logo">

            <h1><strong>Devem.anager</strong></h1>

            <h4>Seja Bem Vindo</h4>

            <form id="form_login" class="form-signin">

              <section>

                <div class="input-group">

                  <input type="text" class="form-control" id="lg_usuario" name="lg_usuario" placeholder="Usuário">
                  <div class="input-group-addon"><i class="fa fa-user"></i></div>

                </div>

                <div class="input-group">

                  <input type="password" class="form-control" name="lg_senha" id="lg_senha" placeholder="Senha">
                  <div class="input-group-addon"><i class="fa fa-key"></i></div>

                </div>

              </section>

              <section class="controls">

                <div class="checkbox check-transparent">
                  <input type="checkbox" value="1" id="contectado" name="contectado">
                  <label for="contectado">Manter conectado</label>
                </div>
                
                <a href="<?=Url::baseAdmin('login/esqueci')?>">Esqueceu a senha?</a>

              </section>

            </form>

              <section class="log-in">

                <button class="btn btn-greensea" id="bt_login" >Logar</button>
              </section>

          </div>

        </div>
        <!-- /Page content --> 

      </div>

    </div>
    <!-- Wrap all page content end -->

  </body>

</html>
      