<!DOCTYPE html>
<html>
  <head>

    <title>Representantes Água Rocha Branca</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8" />

    <link rel="icon" type="image/ico" href="<?=Url::imgApp('icone/favicon.ico')?>" />

    <?php require_once('core/include.scripts-adm.core.php');?>

  </head>

  <body class="bg-1a">

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Make page fluid -->
      <div class="row">

        <!-- Page content -->
        <div id="content" class="col-md-12 full-page login">

          <div class="inside-block">

            <img src="<?=Url::imgApp('logo-agua-rocha-branca.png', false, true)?>" alt class="logo">

            <h1><strong>Devem.anager</strong></h1>

            <h4>Redefinição</h4>
            <br />
            <h5>Infelizmente não encontramos o seu código de desbloqueio, tente redefinir novamente ou entre em contato com o administrador do sistema.</h5>
            <br />
            
            <section class="log-in">
              <button class="btn btn-slategray" id="bt_retorna">Voltar</button>
            </section>

          </div>

        </div>
        <!-- /Page content -->  

      </div>

    </div>
    <!-- Wrap all page content end -->

  </body>

</html>
      