<? $p = $this->pParametros(); ?>
<!DOCTYPE html>
<html>
  <head>
    <title>Água Rocha Branca - Cadastro</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8" />

    <link rel="icon" type="image/ico" href="<?=Url::imgApp('icone/favicon.ico')?>" />

    <?php require_once('core/include.scripts-adm.core.php');?>

  </head>
  <body class="bg-1">
    <!-- Wrap all page content here -->
    <div id="wrap">
      <!-- Make page fluid -->
      <div class="row">
        <!-- Page content -->
        <div id="content" class="col-md-12 full-page login">


          <div class="inside-block">
            <img src="<?=Url::imgApp('logo-agua-rocha-branca.png')?>" alt class="logo">
            <h1>Representantes <strong>Rocha Branca</strong></h1>
            <h4>Cadastro</h4>

            <form id="form_cadastro" class="form-signin">
              <div class="row">


                <div class="input-group col-sm-12">
                  <select class="chosen-select chosen-transparent form-control form-devem-rec" id="cd_representante" name="cd_representante">
                    <option value="">Selecione o Representante</option>
                    <? if(!empty($p)){ foreach ($p as $k) { ?>
                      
                    <option value="<?=$k['ID']?>"><?=$k['user_login']?></option>

                    <? } } ?>
                  </select>
                </div>

                <div class="input-group col-sm-6">

                  <input type="text" class="form-control form-devem-rec" id="cd_nickname" name="cd_nickname" placeholder="Nome de usuário">
                  <div class="input-group-addon"><i class="fa fa-user"></i></div>

                </div>
                <div class="input-group">
                  <input type="text" class="form-control form-devem-rec mascara-cpf" id="cd_cpf" name="cd_cpf" placeholder="CPF">
                  <div class="input-group-addon"><i class="fa fa-user"></i></div>
                </div>
                <div class="input-group col-sm-6">
                  <input type="text" class="form-control form-devem-rec" id="cd_nome" name="cd_nome" placeholder="Nome">
                  <div class="input-group-addon"><i class="fa fa-user"></i></div>
                </div>
                <div class="input-group">
                  <input type="text" class="form-control form-devem-rec" id="cd_sobrenome" name="cd_sobrenome" placeholder="Sobrenome">
                  <div class="input-group-addon"><i class="fa fa-user"></i></div>
                </div>
                <div class="input-group col-sm-6">
                  <select class="chosen-select chosen-transparent form-control form-devem-rec" id="cd_tipo" name="cd_tipo">
                    <option value="1">Pessoa Física</option>
                    <option value="2">Pessoa Juridica</option>
                  </select>
                </div>
                <div class="input-group">
                  <input type="text" class="form-control form-devem-rec mascara-cep" id="cd_cep" name="cd_cep" placeholder="CEP">
                  <div class="input-group-addon"><i class="fa fa-map-marker"></i></div>
                </div>
                <div class="input-group">
                  <input type="text" class="form-control form-devem-rec" id="cd_endereco" name="cd_endereco" placeholder="Endereço">
                  <div class="input-group-addon"><i class="fa fa-map-marker"></i></div>
                </div>
                <div class="input-group col-sm-6">
                  <input type="text" class="form-control form-devem-rec" id="cd_numero" name="cd_numero" placeholder="Número">
                  <div class="input-group-addon"><i class="fa fa-map-marker"></i></div>
                </div>
                <div class="input-group">
                  <input type="text" class="form-control" id="cd_complemento" name="cd_complemento" placeholder="Complemento">
                  <div class="input-group-addon"><i class="fa fa-map-marker"></i></div>
                </div>
                <div class="input-group col-sm-6">
                  <input type="text" class="form-control" id="cd_bairro" name="cd_bairro" placeholder="Bairro">
                  <div class="input-group-addon"><i class="fa fa-map-marker"></i></div>
                </div>
                <div class="input-group">
                  <input type="text" class="form-control form-devem-rec" id="cd_cidade" name="cd_cidade" placeholder="Cidade">
                  <div class="input-group-addon"><i class="fa fa-map-marker"></i></div>
                </div>
                <div class="input-group col-sm-6">
                  <input type="text" class="form-control form-devem-rec" id="cd_estado" name="cd_estado" placeholder="Estado">
                  <div class="input-group-addon"><i class="fa fa-map-marker"></i></div>
                </div>
                <div class="input-group">
                  <input type="text" class="form-control" id="cd_pais" name="cd_pais" placeholder="País">
                  <div class="input-group-addon"><i class="fa fa-map-marker"></i></div>
                </div>
                <div class="input-group col-sm-6">
                  <input type="text" class="form-control form-devem-rec mascara-telefone" id="cd_telefone" name="cd_telefone" placeholder="Telefone">
                  <div class="input-group-addon"><i class="fa fa-phone-square"></i></div>
                </div>
                <div class="input-group">
                  <input type="text" class="form-control mascara-telefone" id="cd_celular" name="cd_celular" placeholder="Celular">
                  <div class="input-group-addon"><i class="fa fa-phone-square"></i></div>
                </div>
                <div class="input-group col-sm-6">
                  <input type="text" class="form-control form-devem-rec" id="cd_email" name="cd_email" placeholder="E-mail">
                  <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                </div>
                <div class="input-group">
                  <input type="text" class="form-control form-devem-rec" id="cd_email_conf" name="cd_email_conf" placeholder="Confirmar E-mail">
                  <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                </div>
                <div class="input-group col-sm-6">
                  <input type="password" class="form-control form-devem-rec" name="cd_senha" id="cd_senha" placeholder="Senha">
                  <div class="input-group-addon"><i class="fa fa-key"></i></div>
                </div>
                <div class="input-group">
                  <input type="password" class="form-control form-devem-rec" name="cd_senha_conf" id="cd_senha_conf" placeholder="Confirma Senha">
                  <div class="input-group-addon"><i class="fa fa-key"></i></div>
                </div>


                  

                  <div class="input-group bt-confirm">
                    <div class="col-sm-12">

                        <input type="checkbox" id="bt_termo_check" value="1">
                        <label for="opt01">Li e aceito os <button class="btn btn-link bt-termo" id="bt_termo" >Termos de Uso</button></label>

                     
                    </div>
                  </div>


                  

                  <div class="input-group bt-confirm">
                    <div class="col-sm-12">
                        <input type="checkbox" id="bt_politica_check" value="1">
                        <label for="opt02">Li e compreendo a <button class="btn btn-link bt-termo" id="bt_politica">Política de Privacidade</button></label>
                    </div>
                  </div>


                <section class="log-in">
                  <button class="btn btn-greensea" id="bt_cadastrar" >Cadastrar</button>
                  <button class="btn btn-slategray" id="bt_retorna">Voltar</button>
                </section>



              </div>
            </form>
                
          </div>


        </div>
        <!-- /Page content -->  
      </div>
    </div>
    <!-- Wrap all page content end -->

      <script src="<?=Url::base('core/js/vendor/chosen/chosen.jquery.min.js')?>"></script>

      <script>

      $(".chosen-select").chosen({disable_search_threshold: 10});

      </script>

  </body>
</html>
      