<? $p = $this->pParametros(); ?>
<!DOCTYPE html>
<html>
  <head>
    <title>Devem Admin - Dvillagra</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <meta name="description" content="Devem Admin - Dvillagra" />

    <meta name="author" content="Dvillagra" />

    <link rel="shortcut icon" href="<?=Url::baseAdmin('view/img/favicon.ico')?>">

    <?php include('admin/include/scriptMenu.admin.php');?>
    <script src="<?=Url::baseAdmin('view/js/Login.class.js')?>"></script>

  </head>

  <body>

    <!-- Main Container start -->
    <div class="dashboard-container">

      <div class="container">

        <!-- Row Start -->
        <div class="row">
          <div class="col-lg-4 col-md-4 col-md-offset-4">
            <div class="sign-in-container">
              <form class="login-wrapper" id="form_login">
                <div class="header">
                  <div class="row">
                    <div class="col-md-12 col-lg-12">
                      <h3>Devem Admin<img src="img/logo1.png" alt="Logo" class="pull-right"></h3>
                    </div>
                  </div>
                </div>
                <div class="content">
                  <div class="form-group">
                    <label for="userName">Usuário</label>
                    <input type="text" class="form-control" id="lg_usuario" name="lg_usuario" placeholder="Usuário">
                  </div>
                  <div class="form-group">
                    <label for="Password1">Senha</label>
                    <input type="password" class="form-control" name="lg_senha" id="lg_senha" placeholder="Senha">
                  </div>
                </div>
                <div class="actions">
                  <input class="btn btn-danger" id="bt_login" type="button" value="Logar">
                  <a class="link" href="#">Esqueceu a senha?</a>
                  <div class="clearfix"></div>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- Row End -->
        
      </div>
    </div>
    <!-- Main Container end -->
    
    <script src="<?=Url::baseAdmin('view/js/bootstrap.min.js')?>"></script>

  </body>
</html>