<? $p = $this->pParametros(); ?>
<!DOCTYPE html>
<html>
  <head>
    <title>Devem Admin - Dvillagra</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <meta name="description" content="Devem Admin - Dvillagra" />

    <meta name="author" content="Dvillagra" />

    <link rel="shortcut icon" href="<?=Url::baseAdmin('view/img/favicon.ico')?>">

    <?php include('admin/include/scriptMenu.admin.php');?>

  </head>

  <body>

    <!-- @HEADER -->
      <?php include('admin/include/header.admin.php');?>
    <!-- @END HEADER -->

        <!-- Sub Nav End -->
        <div class="sub-nav hidden-sm hidden-xs">
          <ul>
            <li><a href="" class="heading">Media</a></li>
          </ul>
          <div class="custom-search hidden-sm hidden-xs">
            <input type="text" class="search-query" placeholder="Buscar ...">
            <i class="fa fa-search"></i>
          </div>
        </div>
        <!-- Sub Nav End -->

        <!-- Dashboard Wrapper Start -->
        <div class="dashboard-wrapper">
          
          <!-- Left Sidebar Start -->
          <div class="left-sidebar">

            <!-- Row Start -->
            <div class="row">
              <div class="col-lg-12 col-md-12">
                <div class="widget">
                  <div class="widget-header">
                    <div class="title">
                      Default thumbnails
                    </div>
                  </div>
                  <div class="widget-body">
                    <!-- Row Start -->
                    <div class="row">
                      <div class="col-xs-6 col-md-3">
                        <a href="#" class="thumbnail no-margin">
                          <img data-src="holder.js/100%x180" alt="100%x180" src="img/saturation.png" style="height: 180px; width: 100%; display: block;">
                        </a>
                      </div>
                      <div class="col-xs-6 col-md-3">
                        <a href="#" class="thumbnail no-margin">
                          <img data-src="holder.js/100%x180" alt="100%x180" src="img/saturation.png" style="height: 180px; width: 100%; display: block;">
                        </a>
                      </div>
                      <div class="col-xs-6 col-md-3">
                        <a href="#" class="thumbnail no-margin">
                          <img data-src="holder.js/100%x180" alt="100%x180" src="img/saturation.png" style="height: 180px; width: 100%; display: block;">
                        </a>
                      </div>
                      <div class="col-xs-6 col-md-3">
                        <a href="#" class="thumbnail no-margin">
                          <img data-src="holder.js/100%x180" alt="100%x180" src="img/saturation.png" style="height: 180px; width: 100%; display: block;">
                        </a>
                      </div>
                    </div>
                    <!-- Row End -->
                  </div>
                </div>
              </div>
            </div>
            <!-- Row End -->

            <!-- Row Start -->
            <div class="row">
              <div class="col-lg-12 col-md-12">
                <div class="widget">
                  <div class="widget-header">
                    <div class="title">
                      Highly customizable
                    </div>
                  </div>
                  <div class="widget-body clearfix">
                    <div class="row">
                      <div class="col-sm-6 col-md-4">
                        <div class="thumbnail">
                          <img data-src="holder.js/300x200" alt="300x200" src="img/saturation.png" style="width: 300px; height: 200px;">
                          <div class="caption">
                            <h3>Thumbnail label</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-6 col-md-4">
                        <div class="thumbnail">
                          <img data-src="holder.js/300x200" alt="300x200" src="img/saturation.png" style="width: 300px; height: 200px;">
                          <div class="caption">
                            <h3>Thumbnail label</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-6 col-md-4">
                        <div class="thumbnail">
                          <img data-src="holder.js/300x200" alt="300x200" src="img/saturation.png" style="width: 300px; height: 200px;">
                          <div class="caption">
                            <h3>Thumbnail label</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- Row End -->

          </div>
          <!-- Left Sidebar End -->

          <!-- Right Sidebar Start -->
          <div class="right-sidebar">
            <div class="wrapper">
              <div class="list-group no-margin">
                <a href="javascript:;" class="list-group-item">
                  <span class="pull-right">
                    <i class="fa fa-file fa-3x text-info"></i>
                  </span>
                  <h4 class="list-group-item-heading">239</h4>
                  <p class="list-group-item-text">Files</p>
                </a>
                <a href="javascript:;" class="list-group-item">
                  <span class="pull-right">
                    <i class="fa fa-check-square-o fa-3x text-warning"></i>
                  </span>
                  <h4 class="list-group-item-heading">11689</h4>
                  <p class="list-group-item-text">Paid</p>
                </a>
                <a href="javascript:;" class="list-group-item">
                  <span class="pull-right">
                    <i class="fa fa-users fa-3x text-success"></i>
                  </span>
                  <h4 class="list-group-item-heading">831</h4>
                  <p class="list-group-item-text">Friends</p>      
                </a>
              </div>
            </div>

          </div>
          <!-- Right Sidebar End -->

        </div>
        <!-- Dashboard Wrapper End -->

        <!-- @FOOTER -->
        <?php include('admin/include/footer.admin.php');?>
      <!-- @END FOOTER -->
      
      </div>
    </div>
    <!-- Main Container end -->

    <script src="<?=Url::baseAdmin('view/js/jquery.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/bootstrap.min.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/jquery.scrollUp.js')?>"></script>

    <!-- Custom JS -->
    <script src="<?=Url::baseAdmin('view/js/menu.js')?>"></script>
    
    <script type="text/javascript">
      //ScrollUp
      $(function () {
        $.scrollUp({
          scrollName: 'scrollUp', // Element ID
          topDistance: '300', // Distance from top before showing element (px)
          topSpeed: 300, // Speed back to top (ms)
          animation: 'fade', // Fade, slide, none
          animationInSpeed: 400, // Animation in speed (ms)
          animationOutSpeed: 400, // Animation out speed (ms)
          scrollText: 'Top', // Text for element
          activeOverlay: false, // Set CSS color to display scrollUp active point, e.g '#00FFFF'
        });
      });

      //Tooltip
      $('a').tooltip('hide');

      //Popover
      $('.popover-pop').popover('hide');

      //Dropdown
      $('.dropdown-toggle').dropdown();

    </script>

  </body>
</html>