<? $p = $this->pParametros(); ?>

<div class="content-modal col-md-12">

	<h3>Cadastro de Novo Parametro</h3>

	<br />

	<p>Insira os dados do novo parametro abaixo</p>

	<section class="tile color transparent parametro">

		<div class="tile-body">

			<form role="form" class="form-horizontal" id="form_parametro_novo">
		                      
		      <div class="form-group">
		        <label class="col-sm-4 control-label" for="pr_nv_alias">Alias</label>
		        <div class="col-sm-8">
		          <input type="text" id="pr_nv_alias" name="pr_nv_alias" class="form-control">
		        </div>
		      </div>
		                      
		      <div class="form-group">
		        <label class="col-sm-4 control-label" for="pr_nv_chave">Chave</label>
		        <div class="col-sm-8">
		          <input type="text" id="pr_nv_chave" name="pr_nv_chave" class="form-control form-devem-rec">
		        </div>
		      </div>
		                      
		      <div class="form-group">
		        <label class="col-sm-4 control-label" for="pr_nv_valor_default">Valor Default</label>
		        <div class="col-sm-8">
		          <input type="text" id="pr_nv_valor_default" name="pr_nv_valor_default" class="form-control form-devem-rec">
		        </div>
		      </div>
		                      
		      <div class="form-group">
		        <label class="col-sm-4 control-label" for="pr_nv_descricao">Descrição</label>
		        <div class="col-sm-8">
		          <input type="text" id="pr_nv_descricao" name="pr_nv_descricao" class="form-control">
		        </div>
		      </div>

		    </form>
		</div>
	</section>
	
	<button class='btn bt-ok'>Salvar</button>
	<button class='btn bt-cancel'>Cancelar</button>

	<input type="hidden" id="acao" value="devem.parametro.gravar();" />

</div>
 
 <script> 

 	$('.content-modal .bt-ok').click(function(){

 		eval($("#acao").val());

 	}); 

 	$('.content-modal .bt-cancel').click(function(){

 		$.fancybox.close();

 	}); 

 </script>