<? $p = $this->pParametros(); ?>

<div class="content-modal">

	<h3>
TERMO DE ADESÃO E REGRAS DO PROGRAMA DE REPRESENTANTES ROCHA BRANCA

</h3>
	<br />
	<p>

Este Termo contém todas as regras que se aplicam à filiação de indivíduos no Programa de Representantes ROCHA BRANCA, doravante chamado de “Programa”, onde os REPRESENTANTES previamente aprovados pela ROCHA BRANCA e os CLIENTES por eles representados poderão encomendar produtos que constem do catálogo do site (“Produtos”).

</p>
	<br />
	<p>

<b>1. Registro no Programa:</b>

</p>
	<br />
	<p>

a) O candidato a REPRESENTANTE e o CLIENTE, que deverão ser pessoas físicas, maiores de 18 anos e plenamente capazes, devem preencher o formulário do site da ROCHA BRANCA com as informações requisitadas, comprometendo-se à veracidade das mesmas.

</p>
	<br />
	<p>

b) A ROCHA BRANCA avaliará os dados do candidato e do CLIENTE, reservando-se ao direito de recusar seu registro caso o seu perfil não se adeque ao Programa, por quaisquer motivos que a ROCHA BRANCA julgue necessário.

</p>
	<br />
	<p>

c) Ao ser aceito, o candidato receberá um e-mail comunicando que se tornou um REPRESENTANTE e receberá o número de afiliado – que servirá para sua identificação.

</p>
	<br />
	<p>

d) Após a regularização do cadastro, o REPRESENTANTE deverá indicar o seu número de identificação aos seus CLIENTES, que deverão incluí-lo no seu cadastro no site da ROCHA BRANCA ou no pedido de produtos feito diretamente por eles, para que assim o REPRESENTANTE tenha direito às comissões elencadas neste Termo, segundo as regras aqui expostas.

</p>
	<br />
	<p>

e) O REPRESENTANTE não poderá oferecer qualquer incentivo, descontos ou outros benefícios para os CLIENTES, que serão os únicos responsáveis pelo pagamento referente ao produto encomendado, devendo estes serem realizados no momento do recebimento do Produto pelo CLIENTE.

</p>
	<br />
	<p>

f) A comissão somente será devida caso seja feito, pelo CLIENTE, o pagamento REFERENTE aos produtos que foram encomendados.

</p>
	<br />
	<p>

g) O REPRESENTANTE não possui forma alguma de exclusividade de representação da ROCHA BRANCA.

</p>
	<br />
	<p>

h) O CLIENTE não poderá ter mais que um REPRESENTANTE vinculado a seu nome.

</p>
	<br />
	<p>

i) REPRESENTANTE e CLIENTE não pagam nenhum valor para se tornar um afiliado ao Programa.

</p>
	<br />
	<p>

j) REPRESENTANTE e CLIENTE comprometem-se a prestar informações verdadeiras, responsabilizando-se civil e criminalmente pela autenticidade dessas e assumindo o compromisso de atualização dos dados informados em caso de alteração, em especial o endereço e telefone.

</p>
	<br />
	<p>

k) REPRESENTANTE e CLIENTE concordam expressamente que a inserção de seus dados cadastrais nas bases de dados da ROCHA BRANCA não constitui violação de sua intimidade, vida privada, honra e/ou imagem, em virtude da natureza do cadastro.

</p>
	<br />
	<p>

l) O REPRESENTANTE fica ciente, neste ato, que o simples cadastro realizado na plataforma da ROCHA BRANCA não representa qualquer garantia de vendas ou qualquer espécie de exclusividade no relacionamento entre as partes.

</p>
	<br />
	<p>

m) Após a validação do cadastro realizado, o acesso à plataforma da ROCHA BRANCA será feito pelo REPRESENNTANTE ou CLIENTE mediante o emprego de login e senha, a serem cadastrados no primeiro acesso.

</p>
	<br />
	<p>

n) O login e senha de acesso à plataforma da ROCHA BRANCA é de uso exclusivo, pessoal e intransferível da pessoa que realizou o cadastro, assumindo estes desde já integral responsabilidade pela guarda e sigilo dos mesmos, bem como pelo uso indevido por terceiros.

</p>
	<br />
	<p>

<b>2. Pedido de Galões de Água ROCHA BRANCA:</b>

</p>
	<br />
	<p>

a) Os pedidos de produtos ROCHA BRANCA poderão ser feitos diretamente pelo CLIENTE, ou pelo REPRESENTANTE, pelo site da ROCHA BRANCA ou por telefone.

</p>
	<br />
	<p>

b) O REPRESENTANTE, para proceder a realização dos pedidos via internet em nome do CLIENTE, deverá estar logado na página web da ROCHA BRANCA. Tanto nos pedidos por internet, como por telefone, o CLIENTE deverá estar previamente cadastrado e vinculado ao número de identificação de seu REPRESENTANTE, após confirmação de cadastro pelo próprio CLIENTE.

</p>
	<br />
	<p>

c) Após o REPRESENTANTE realizar um pedido em nome de algum CLIENTE seu, este receberá um e-mail de confirmação do pedido efetuado. Os produtos encomendados somente sairão do centro de distribuição ROCHA BRANCA, para serem entregues ao CLIENTE, após este confirmar o pedido feito em seu nome.

</p>
	<br />
	<p>

d) O CLIENTE é o único responsável pelo pagamento dos produtos requisitados, que deverá ser efetuado no momento de entrega dos mesmos no endereço cadastrado.

</p>
	<br />
	<p>

e) Na ocasião do pedido, o CLIENTE deverá informar o número de identificação do REPRESENTANTE, para que este acumule pontos que lhe darão o direito ao recebimento da referida comissão.

</p>
	<br />
	<p>

f) Ao confirmar o cadastro na plataforma da ROCHA BRANCA, o REPRESENTANTE se declara plenamente ciente de que será o único responsável pelas operações realizadas através de seu login, cujo acesso somente será permitido após o fornecimento da senha de uso exclusivo, pessoal e intransferível.

</p>
	<br />
	<p>

<b>3. Comissão sobre vendas</b>

</p>
	<br />
	<p>

a) A ROCHA BRANCA pagará ao REPRESENTANTE uma comissão de R$1,00 (um real) por galão de água comprado pelo CLIENTE, independentemente da litragem do mesmo, desde que, no momento da compra, o seu número de identificação esteja vinculado ao pedido e este tenha sido aprovado pelo CLIENTE.

</p>
	<br />
	<p>

b) O valor da comissão pode ser alterado pela ROCHA BRANCA a qualquer momento, sem que haja a necessidade de prévia comunicação ao REPRESENTANTE ou CLIENTE, também podendo ser extinta a qualquer momento por decisão unilateral, sem necessidade de justificativa

</p>
	<br />
	<p>

c) O pagamento da comissão sobre as vendas será realizado pela ROCHA BRANCA ao REPRESENTANTE após este acumular o mínimo de R$50,00 (cinquenta reais) em valor devido, em até 10 dias após a requisição de pagamento da comissão, feita pelo REPRESENTANTE diretamente no site da ROCHA BRANCA.

</p>
	<br />
	<p>

d) A comissão poderá ser paga ao REPRESENTANTE tanto em produtos ROCHA BRANCA como mediante depósito em conta corrente em seu nome.

</p>
	<br />
	<p>

e) Apenas os pedidos faturados e pagos serão considerados como vendas, para que se possa considerar devida a comissão.

</p>
	<br />
	<p>

f) REPRESENTANTE e CLIENTE receberão ao final de cada mês um relatório por e-mail com as informações das vendas realizadas em vínculo com o seu número de identificação.

</p>
	<br />
	<p>

g) O REPRESENTANTE só terá direito a receber comissões sobre vendas efetuadas durante a vigência deste Termo. As comissões sobre as vendas de Produtos realizadas antes do seu término só serão pagas, caso os pedidos de Produtos em questão não sejam cancelados ou devolvidos e desde que os o valor referente tenha sido integralmente pago à ROCHA BRANCA.

</p>
	<br />
	<p>

<b>4. Responsabilidades do REPRESENTANTE:</b>

</p>
	<br />
	<p>

a) O REPRESENTANTE será o único responsável pela veracidade dos dados fornecidos no cadastro e pela atração de CLIENTES para efetuarem as compras com o seu número de identificação.

</p>
	<br />
	<p>

b) O REPRESENTANTE é responsável por assegurar que a operação de venda não viole ou infrinja direitos de terceiros (incluindo, direitos autorais, marcas, e outros direitos de propriedade intelectual e de imagem), assegurando que jamais utilize-se de material difamatório ou ilegal.

</p>
	<br />
	<p>

c) A ROCHA BRANCA não tem qualquer responsabilidade pelas indicações ou informações veiculadas e fornecidas pelo REPRESENTANTE aos CLIENTES.

</p>
	<br />
	<p>

d) O REPRESENTANTE compromete-se a efetuar os pedidos estritamente de acordo com as requisições de seu CLIENTE, não podendo este ser responsabilizado por pedidos errados.

</p>
	<br />
	<p>

<b>5. Condições Gerais</b>

</p>
	<br />
	<p>

a) Este Termo terá início na data em que o seu registro no Programa de Representantes ROCHA BRANCA for aceito.

</p>
	<br />
	<p>

b) Qualquer CLIENTE que comprar através deste Programa será considerado cliente da ROCHA BRANCA.

</p>
	<br />
	<p>

c) A ROCHA BRANCA tem direito de alterar as regras, valores e procedimentos da operação de compra e do Programa de representantes a qualquer momento, independentemente de prévia comunicação. Os preços de Produtos podem variar de acordo com o mercado.

</p>
	<br />
	<p>

d) É estritamente proibida a divulgação de preços ou quaisquer informações sobre os Produtos ou promoções da ROCHA BRANCA pelo REPRESENTANTE, que não tenham sido previamente aprovadas pela empresa, sob pena de exclusão do Programa.

</p>
	<br />
	<p>

f) Os direitos de propriedade sobre todos os ícones, mensagens e outras imagens, assim como do nome e da marca registrada, são pertencentes à Água Mineral ROCHA BRANCA (razão social da empresa).

</p>
	<br />
	<p>

g) O REPRESENTANTE obriga-se a não fazer qualquer uso, ou sob qualquer forma explorar, quaisquer das marcas, nomes e/ou patentes que pertençam à ROCHA BRANCA, a qualquer tempo, sob pena de exclusão do Programa, sem prejuízo de ressarcimento das perdas e danos a que porventura a ROCHA BRANCA tenha direito.

</p>
	<br />
	<p>

h) A ROCHA BRANCA se reserva o direito de, a qualquer tempo, requerer documentação comprobatória das informações disponibilizadas pelo REPRESENTANTE ou CLIENTE, bem como de utilizar meios autônomos para confirmar a veracidade do cadastro.

</p>
	<br />
	<p>

<b>6. Rescisão e Modificação:</b>

</p>
	<br />
	<p>

a) Este Termo poderá ser rescindido imediatamente, a qualquer tempo, unilateralmente por qualquer uma das partes, sem necessidade de justificativa, mediante simples cancelamento do cadastro na plataforma ROCHA BRANCA.

</p>
	<br />
	<p>

b) A ROCHA BRANCA reserva-se o direito de modificar quaisquer regras e condições contidas neste Termo, sem a necessidade de prévia informação, a qualquer tempo, através da simples apresentação por e-mail de um aviso de mudança ou de um novo Termo ao REPRESENTANTE.

</p>
	<br />
	<p>

c) Caso as modificações a serem realizadas neste Termo não sejam aprovadas pelo REPRESENTANTE, cabe a ele o direito de recusar as novas condições e rescindir este Termo. Caso o REPRESENTANTE continue a participar do Programa, após aviso de modificação dos termos do mesmo, isto indicará que o REPRESENTANTE aceitou todas as modificações comunicadas.

</p>
	<br />
	<p>

d) A ROCHA BRANCA poderá reter o pagamento das comissões ao REPRESENTANTE após o término deste Termo, pelo prazo de até 30 (trinta) dias, para assegurar que os últimos pagamentos referentes às vendas de Produtos aos CLIENTES tenham sido efetivados integralmente.

</p>
	<br />
	<p>

<b>7. Relacionamento entre as Partes do Programa de Afiliação</b>

</p>
	<br />
	<p>

a) ROCHA BRANCA, REPRESENTANTE e CLIENTE são partes contratantes independentes e nenhuma das cláusulas deste Termo autoriza ou resulta na criação de qualquer sociedade, franquia ou relação de trabalho entre as partes, bem como implica qualquer solidariedade ou subsidiariedade.

</p>
	<br />
	<p>

b) O REPRESENTANTE não tem autorização para aceitar, fazer quaisquer ofertas ou, de qualquer forma, atuar em nome da ROCHA BRANCA, sendo somente um intermediário nas vendas.

</p>
	<br />
	<p>

c) REPRESENTANTE e CLIENTE não poderão fazer qualquer afirmação, seja por via escrita ou oral, que contradiga quaisquer cláusulas do presente Termo ou que seja prejudicial à imagem da ROCHA BRANCA.

</p>
	<br />
	<p>

d) O recolhimento de tributos que venham a recair sobre o valor da comissão recebida pelo REPRESENTANTE é de sua única e inteira responsabilidade.

</p>
	<br />
	<p>

e) É de inteira responsabilidade do REPRESENTANTE o registro de sua condição no Conselho Regional de Representantes Comerciais, caso entenda necessário.

</p>
	<br />
	<p>

<b>8. Restrições de Responsabilidade:</b>

</p>
	<br />
	<p>

a) A responsabilidade da ROCHA BRANCA perante o REPRESENTANTE refere-se, única e exclusivamente, ao pagamento das comissões sobre as vendas de Produtos a que tenha direito. A ROCHA BRANCA não será, desta

forma, responsável por quaisquer danos, perdas de rendimentos, de lucros ou de informações decorrentes, direta ou indiretamente, advindas da participação do REPRESENTANTE no programa.

</p>
	<br />
	<p>

b) A ROCHA BRANCA não será responsável por interrupções ou erros que ocorram na transmissão de dados via Internet.

</p>
	<br />
	<p>

c) REPRESENTANTE e CLIENTE ficam cientes que, sempre que fundado em indício de ato ilícito e solicitados por qualquer interessado, seus dados fornecidos no ato do cadastro, será lícito à ROCHA BRANCA fornecer os dados almejados, inclusive registros eletrônicos, a seu exclusivo critério, sem que tal ato constitua qualquer violação de sigilo.

</p>
	<br />
	<p>

d) REPRESENTANTE e CLIENTE concordam e declaram expressamente que o fornecimento de seus dados cadastrais e registros eletrônicos a terceiros não constitui violação de sua intimidade, vida privada, honra e/ou imagem, em virtude da natureza destes dados.

</p>
	<br />
	<p>

e) REPRESENTANTE e CLIENTE declaram que todos os dados eventualmente fornecidos são verdadeiros, sob as penas da lei.

</p>
	<br />
	<p>

f) Os direitos e obrigações ora pactuados, bem como a eventual senha de acesso à plataforma da ROCHA BRANCA, não poderão ser transferidos ou cedidos pelo REPRESENTANTE ou CLIENTE a terceiros, sob qualquer condição, sendo que sua utilização indevida isenta a ROCHA BRANCA de qualquer responsabilidade.

</p>
	<br />
	<p>

g) A tolerância de uma parte para com a outra, relativamente a descumprimento de qualquer das obrigações ora assumidas, não será considerada novação ou renúncia a qualquer direito, constituindo mera liberalidade, que não impedirá a parte tolerante de exigir da outra o fiel cumprimento deste contrato, a qualquer tempo.

</p>
	<br />
	<p>

<b>9. Guarda de Dados</b>

</p>
	<br />
	<p>

a) Ao realizar o cadastro, REPRESENTANTE e CLIENTE autorizam automaticamente a ROCHA BRANCA a armazenar e utilizar os dados cadastrais fornecidos no ato do cadastro, bem como todos os registros eletrônicos de criação e acessos à conta.

</p>
	<br />
	<p>

b) Os dados e registros eletrônicos do REPRESENTANTE e CLIENTE são armazenados pela plataforma da ROCHA BRANCA, de forma criptografada e totalmente eletrônica, pelo período que esta entender conveniente, a seu exclusivo critério.

</p>
	<br />
	<p>

c) A ROCHA BRANCA não se responsabiliza por falhas no sistema ou atos de terceiros que logrem êxito em coletar ou utilizar, por quaisquer meios, dados cadastrais e informações disponibilizadas pelo REPRESENTANTE ou CLIENTE no ato do cadastro.

</p>
	<br />
	<p>

d) As informações de cadastro, conteúdo e registro eletrônicos do REPRESENTANTE e CLIENTE poderão ser utilizadas de maneira irrestrita pela ROCHA BRANCA, sempre para fins lícitos, com o objetivo específico de gerir e atingir o objeto do presente documento.

</p>
	<br />
	<p>

e) REPRESENTANTE e CLIENTE concordam e declaram expressamente que, pela natureza dos dados que fornecem à ROCHA BRANCA, estes não constituem correspondência, comunicação telegráfica, dados ou comunicações telefônicas.

</p>
	<br />
	<p>

<b>10. Foro:</b>

</p>
	<br />
	<p>

Fica eleito o Foro Central da cidade de São Paulo como competente para solucionar eventuais controvérsias decorrentes do presente Termo.

</p>
	<br />
	<p>

<b>11. Aceitação dos Termos:</b>

</p>
	<br />
	<p>

a) REPRESENTANTE e CLIENTE declaram e garantem possuir plena capacidade jurídica para a celebração do presente Termo.

</p>
	<br />
	<p>

b) REPRESENTANTE e CLIENTE declaram que avaliaram e aceitam a sua participação no Programa de Representantes ROCHA BRANCA, concordando com todos os termos e condições do presente Termo. Reconhecem, também, que a ROCHA BRANCA poderá, a qualquer tempo, solicitar suas referências, assim como operar em parceria com outras entidades e indivíduos que atuem na mesma área de negócios.

</p>
	<br />
	<p>
A ROCHA BRANCA reserva-se o direito de, a qualquer momento, modificar, alterar, acrescentar ou remover partes deste termo de política de privacidade.</p>
	
	<button class='btn bt-ok'>Fechar</button>

</div>
 
 <script> 

 	$('.content-modal .bt-ok').click(function(){

 			$.fancybox.close();
 	}); 

 </script>