<? $p = $this->pParametros(); ?>
<!DOCTYPE html>
<html>
  <head>
    <title>Devem Admin - Dvillagra</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <meta name="description" content="Devem Admin - Dvillagra" />

    <meta name="author" content="Dvillagra" />

    <link rel="shortcut icon" href="<?=Url::baseAdmin('view/img/favicon.ico')?>">

    <?php include('admin/include/scriptMenu.admin.php');?>

  </head>

  <body>

    <!-- @HEADER -->
      <?php include('admin/include/header.admin.php');?>
    <!-- @END HEADER -->

        <!-- Sub Nav End -->
        <div class="sub-nav hidden-sm hidden-xs">
          <ul>
            <li><a href="" class="heading">Painel</a></li>
          </ul>
          <div class="custom-search hidden-sm hidden-xs">
            <input type="text" class="search-query" placeholder="Buscar ...">
            <i class="fa fa-search"></i>
          </div>
        </div>
        <!-- Sub Nav End -->

        <!-- Dashboard Wrapper Start -->
        <div class="dashboard-wrapper">
          
          <!-- Left Sidebar Start -->
          <div class="left-sidebar">

            <!-- Row starts -->
            <div class="row">
              <div class="col-lg-4 col-md-4 col-sm-12 col-sx-12">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title"><i class="icon ion-clock text-success"></i> Panel Default</h4>
                  </div>
                  <div class="panel-body">
                    
                  </div>
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12 col-sx-12">
                <div class="panel panel-success">
                  <div class="panel-heading">
                    <h4 class="panel-title"><i class="icon ion-clock text-success"></i> Panel Success</h4>
                  </div>
                  <div class="panel-body">
                    
                  </div>
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12 col-sx-12">
                <div class="panel panel-warning">
                  <div class="panel-heading">
                    <h4 class="panel-title"><i class="icon ion-clock text-warning"></i> Panel Warning</h4>
                  </div>
                  <div class="panel-body">
                    
                  </div>
                </div>
              </div>
            </div>
            <!-- Row ends -->

            <!-- Row starts -->
            <div class="row">
              <div class="col-lg-4 col-md-4 col-sm-12 col-sx-12">
                <div class="panel panel-danger">
                  <div class="panel-heading">
                    <h4 class="panel-title"><i class="icon ion-clock text-danger"></i> Panel Default</h4>
                  </div>
                  <div class="panel-body">
                    
                  </div>
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12 col-sx-12">
                <div class="panel panel-info">
                  <div class="panel-heading">
                    <h4 class="panel-title"><i class="icon ion-clock text-info"></i> Panel Info</h4>
                  </div>
                  <div class="panel-body">
                    
                  </div>
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12 col-sx-12">
                <div class="panel panel-yell">
                  <div class="panel-heading">
                    <h4 class="panel-title"><i class="icon ion-clock text-yellow"></i> Panel Yellow</h4>
                  </div>
                  <div class="panel-body">
                    
                  </div>
                </div>
              </div>
            </div>
            <!-- Row ends -->

            <!-- Row starts -->
            <div class="row">
              <div class="col-lg-4 col-md-4 col-sm-6 col-sx-12">
                <div class="panel-grey">
                  <h4 class="heading">Panel Dark Grey</h4>
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-6 col-sx-12">
                <div class="panel-white">
                  <h4 class="heading">Panel White</h4>
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12 col-sx-12">
                <div class="panel-red">
                  <h4 class="heading">Panel Danger</h4>
                </div>
              </div>
            </div>
            <!-- Row ends -->

            <!-- Row starts -->
            <div class="row">
              <div class="col-lg-4 col-md-4 col-sm-6 col-sx-12">
                <div class="panel-green">
                  <h4 class="heading">Panel Success</h4>
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-6 col-sx-12">
                <div class="panel-teal">
                  <h4 class="heading">Panel Teal</h4>
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12 col-sx-12">
                <div class="panel-yellow">
                  <h4 class="heading">Panel Yellow</h4>
                </div>
              </div>
            </div>
            <!-- Row ends -->

            <!-- Row starts -->
            <div class="row">
              <div class="col-lg-4 col-md-4 col-sm-6 col-sx-12">
                <div class="panel-brown">
                  <h4 class="heading">Panel Brown</h4>
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-6 col-sx-12">
                <div class="panel-orange">
                  <h4 class="heading">Panel Orange</h4>
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12 col-sx-12">
                <div class="panel-blue">
                  <h4 class="heading">Panel Info</h4>
                </div>
              </div>
            </div>
            <!-- Row ends -->

            <!-- Row starts -->
            <div class="row">
              <div class="col-lg-4 col-md-4 col-sm-6 col-sx-12">
                <div class="panel-fb">
                  <h4 class="heading">Panel Facebook</h4>
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-6 col-sx-12">
                <div class="panel-twitter">
                  <h4 class="heading">Panel Twitter</h4>
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12 col-sx-12">
                <div class="panel-linkedin">
                  <h4 class="heading">Panel Linkedin</h4>
                </div>
              </div>
            </div>
            <!-- Row ends -->

            <!-- Row Start -->
            <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="widget">
                  <div class="widget-header">
                    <div class="title">
                      Panel basic example
                    </div>
                  </div>
                  <div class="widget-body">
                    <div class="panel panel-default no-margin">
                      <div class="panel-body">
                        Basic panel example
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- Row End -->

          </div>
          <!-- Left Sidebar End -->

          <!-- Right Sidebar Start -->
          <div class="right-sidebar">
            <div class="wrapper">
              <div class="list-group no-margin">
                <a href="javascript:;" class="list-group-item">
                  <span class="pull-right">
                    <i class="fa fa-file fa-3x text-info"></i>
                  </span>
                  <h4 class="list-group-item-heading">239</h4>
                  <p class="list-group-item-text">Files</p>
                </a>
                <a href="javascript:;" class="list-group-item">
                  <span class="pull-right">
                    <i class="fa fa-check-square-o fa-3x text-warning"></i>
                  </span>
                  <h4 class="list-group-item-heading">11689</h4>
                  <p class="list-group-item-text">Paid</p>
                </a>
                <a href="javascript:;" class="list-group-item">
                  <span class="pull-right">
                    <i class="fa fa-users fa-3x text-success"></i>
                  </span>
                  <h4 class="list-group-item-heading">831</h4>
                  <p class="list-group-item-text">Friends</p>      
                </a>
              </div>
            </div>

          </div>
          <!-- Right Sidebar End -->

        </div>
        <!-- Dashboard Wrapper End -->

        <!-- @FOOTER -->
        <?php include('admin/include/footer.admin.php');?>
      <!-- @END FOOTER -->

      </div>
    </div>
    <!-- Main Container end -->

    <script src="<?=Url::baseAdmin('view/js/jquery.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/bootstrap.min.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/jquery.scrollUp.js')?>"></script>

    <!-- Custom JS -->
    <script src="<?=Url::baseAdmin('view/js/menu.js')?>"></script>
    
    <script type="text/javascript">

      //ScrollUp
      $(function () {
        $.scrollUp({
          scrollName: 'scrollUp', // Element ID
          topDistance: '300', // Distance from top before showing element (px)
          topSpeed: 300, // Speed back to top (ms)
          animation: 'fade', // Fade, slide, none
          animationInSpeed: 400, // Animation in speed (ms)
          animationOutSpeed: 400, // Animation out speed (ms)
          scrollText: 'Top', // Text for element
          activeOverlay: false, // Set CSS color to display scrollUp active point, e.g '#00FFFF'
        });
      });
    </script>

  </body>
</html>