<? 

  $p = $this->pParametros(); 

?>
<!DOCTYPE html>
<html>
  <head>

      <meta charset="utf-8">

      <?php include('core/include.tags.core.php');?>

      <?php require_once('admin/include/include.scripts.admin.php');?>
      
      <script src="<?=Url::baseAdmin('view/js/Parametro.class.js')?>?20150608"></script>  

  </head>

<body class="bg-1a">

    <!-- Preloader -->
    <div class="mask"><div id="loader"></div></div>
    <!--/Preloader -->

    

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Make page fluid -->
      <div class="row">
        
        <!-- @HEADER -->
          <?php include('admin/include/include.header.admin.php');?>
        <!-- @END HEADER -->        
        
        <!-- Page content -->
        <div id="content" class="col-md-12">
          
          <!-- page header -->
          <div class="pageheader">
            
            <h2><i class="fa fa-cog"></i> Parametros</h2>
            
            <div class="breadcrumbs">

              <ol class="breadcrumb">

                <li>Você está em </li>
                <li class="active">Parametros</li>

              </ol>

              <button class="btn btn-slategray" id="bt_novo_parametro" >Novo Parametro</button>

            </div>

          </div>
          <!-- /page header -->
          
          <!-- content main container -->
          <div class="main">

            <!-- cards -->
            <div class="row">

              <div class="col-md-12">

                <section class="tile color transparent-black">

                  <!-- tile header -->
                  <div class="tile-header">

                    <h1>Dados de Parametros </h1>

                  </div>
                  <!-- /tile header -->

                  <!-- tile body -->
                  <div class="tile-body">

                    <form id="form_parametro">
                    
                      <div class="row">

                        <div class="form-group col-sm-1">

                          <label for="exampleInputEmail">ID</label>

                        </div>

                        <div class="form-group col-sm-2">

                          <label for="exampleInputPassword1">Alias</label>
                        
                        </div>

                        <div class="form-group col-sm-2">

                          <label for="exampleInputPassword1">Chave</label>
                        
                        </div>

                        <div class="form-group col-sm-2">

                          <label for="exampleInputPassword1">Valor Default</label>
                        
                        </div>

                        <div class="form-group col-sm-2">

                          <label for="exampleInputPassword1">Valor Atual</label>
                        
                        </div>

                        <div class="form-group col-sm-2">

                          <label for="exampleInputPassword1">Descrição</label>
                        
                        </div>

                        <div class="form-group col-sm-1">

                          <label for="exampleInputPassword1">Ação</label>
                        
                        </div>

                      </div>

                      <? foreach ($p as $k) { ?>
                    
                        <div class="row">

                          <div class="form-group col-sm-1">
                            <input type="text" value="<?=$k['idParametro']?>" readonly="readonly" id="pr_id" name="pr_id[]" class="form-control form-devem-rec">

                          </div>

                          <div class="form-group col-sm-2">
                            <input type="text" value="<?=$k['pAlias']?>" placeholder="Alias" id="pr_alias" name="pr_alias[]" class="form-control form-devem-rec">
                          
                          </div>

                          <div class="form-group col-sm-2">
                            <input type="text" value="<?=$k['pChave']?>" placeholder="Chave" id="pr_chave" name="pr_chave[]" class="form-control form-devem-rec">
                          
                          </div>

                          <div class="form-group col-sm-2">
                            <input type="text" value="<?=(empty($k['pValorDefault']) ? '- - -' : $k['pValorDefault'])?>" readonly="readonly" class="form-control form-devem-rec">
                          
                          </div>

                          <div class="form-group col-sm-2">
                            <input type="text" value="<?=(empty($k['pValorAtual']) ? '- - -' : $k['pValorAtual'])?>" placeholder="Valor Atual" id="pr_valor_atual" name="pr_valor_atual[]" class="form-control form-devem-rec">
                          
                          </div>

                          <div class="form-group col-sm-2">
                            <input type="text" value="<?=(empty($k['pDescricao']) ? '- - -' : $k['pDescricao'])?>" placeholder="Descrição" id="pr_descricao" name="pr_descricao[]" class="form-control form-devem-rec">
                          
                          </div>

                          <div class="form-group col-sm-1">
                            <i class="fa fa-trash-o excluir-parametro" opt-id="<?=$k['idParametro']?>"></i>

                          </div>

                        </div>

                      <? } ?>

                    </form>

                    <section class="log-in">
                     
                      <button class="btn btn-primary " id="bt_salvar_parametros">Salvar Parametros</button>
                    
                    </section>

                  </div>
                  <!-- /tile body -->
                
                </section>



              </div>

            </div>

            <div class="row">


            </div>
            <!-- /cards -->

          </div>
          <!-- /content container -->

        </div>
        <!-- Page content end -->

      </div>
      <!-- Make page fluid-->

    </div>
    <!-- Wrap all page content end -->

    <!-- Include all compiled plugins (below), or include individual files as needed -->

    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap-dropdown-multilevel.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/mmenu/js/jquery.mmenu.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/sparkline/jquery.sparkline.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/nicescroll/jquery.nicescroll.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/animate-numbers/jquery.animateNumbers.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/blockui/jquery.blockUI.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/easypiechart/jquery.easypiechart.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/rickshaw/raphael-min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/rickshaw/d3.v2.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/rickshaw/rickshaw.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/morris/morris.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/tabdrop/bootstrap-tabdrop.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/summernote/summernote.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/chosen/chosen.jquery.min.js')?>"></script>
    <script src="<?=Url::base('core/js/devem/minimal.min.js')?>"></script>

    <script src="<?=Url::base('core/js/vendor/datatables/jquery.dataTables.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/ColReorderWithResize.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/colvis/dataTables.colVis.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/tabletools/ZeroClipboard.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/tabletools/dataTables.tableTools.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/dataTables.bootstrap.js')?>"></script>

    <script>
    $(function(){

      // Initialize card flip
      $('.card.hover').hover(function(){
        $(this).addClass('flip');
      },function(){
        $(this).removeClass('flip');
      });

      //generate actual pie charts
      $('.pie-chart').easyPieChart();

      // sortable table
      $('.table.table-sortable th.sortable').click(function() {
        var o = $(this).hasClass('sort-asc') ? 'sort-desc' : 'sort-asc';
        $('th.sortable').removeClass('sort-asc').removeClass('sort-desc');
        $(this).addClass(o);
      });

      // Initialize tabDrop
      $('.tabdrop').tabdrop({text: '<i class="fa fa-th-list"></i>'});

      //load wysiwyg editor
      $('#msg-box').summernote({
        toolbar: false,
        height: 161   //set editable area's height
      });

      

      $('#make-call a').click(function(){
        $(this).toggleClass('active');
      });

      $('.post-toolbar a').tooltip({
        placement: 'top',
        trigger: 'hover',
        html : true,
        container: 'body'
      }); 

      $('.task-controls .mark').click(function(){
        $(this).toggleClass('marked');
      });

      //accordion class active toggling
      $('.task-list .panel-heading .task-toggle').click(function() {

        var $previous = $( '.task-list .panel.active' );

        $previous.removeClass('active');
        $(this).parent().parent().stop().addClass('active');

        if($(this).parent().parent().hasClass('active')) {
          $previous.removeClass('active');
        }
      });

      //chosen select input
      $(".chosen-select").chosen({disable_search_threshold: 10});

      //initialize file upload button
      $('.btn-file :file').on('fileselect', function(event, numFiles, label) {
        
        var input = $(this).parents('.input-group').find(':text'),
            log = numFiles > 1 ? numFiles + ' files selected' : label;

            console.log(log);
        
        if( input.length ) {
          input.val(log);
        } else {
          if( log ) alert(log);
        }      
      });
      
    })
      
    </script>
  </body>
</html>
