<? $p = $this->pParametros();?>
<!DOCTYPE html>
<html>
  <head
      <meta charset="utf-8">

      <?php include('core/include.tags.core.php');?>

      <?php require_once('core/include.scripts.core.php');?>

      <link rel="stylesheet" href="<?=Url::base('core/js/vendor/superbox/css/style.css')?>" type="text/css" />

      <script  src="<?=Configuracoes::CheckFileCustomer('js/Pedido.class.js', true)?>" ></script>
    
  </head>

  <body class="bg-1">

    <!-- Preloader -->
    <div class="mask"><div id="loader"></div></div>
    <!--/Preloader -->

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Make page fluid -->
      <div class="row">

        <!-- @HEADER -->
          <?php include('core/include.header.core.php');?>
        <!-- @END HEADER -->
        
        <!-- Page content -->
        <div id="content" class="col-md-12">
          
          <!-- page header -->
          <div class="pageheader">
            
            <h2><i class="fa fa-cart-plus" style="line-height: 48px;padding-left: 0;"></i> Produtos <span>// Válidos para pontuação de representantes</span></h2>
            
            <div class="breadcrumbs">

              <ol class="breadcrumb">

                <li>Você está em</li>
                <li><a href="index.html">Pedido</a></li>
                <li><a href="#">Produtos</a></li>

              </ol>

            </div>

          </div>
          <!-- /page header -->
          
          <!-- content main container -->
          <div class="main">        

           <!-- row -->
            <div class="row">

              <!-- col 12 -->
              <div class="col-md-12">
              
                <?
                  foreach ($p as $w => $k) {
                ?>
                <!-- tile body -->

                <div class="col-sm-4">
                <!-- tile -->

                <section class="tile transparent">

                 <!-- tile header -->
                  <div class="tile-header nopadding"> 

                    <div class="controls">

                      <a class="minimize" href="#"><i class="fa fa-chevron-down"></i></a>
                      <!--a class="refresh" href="#"><i class="fa fa-refresh"></i></a>
                      <a class="remove" href="#"><i class="fa fa-times"></i></a-->

                    </div>

                  </div>
                  <!-- /tile header -->

                  <!-- tile widget -->
                  <div class="tile-widget color cyan rounded-top-corners">

                    <div class="fa fa-tint watermark"></div>
                    
                    <div class="media social-feed">   

                      <span class="pull-left">

                        <img  alt="" src="<?=$k['imagem']?>">

                      </span>

                      <div class="media-body">

                        <h4 class="media-heading"><?=$k['produto']?></h4>
                        <small><a href="#"><?=$k['estoque']?></a></small>

                      </div>

                    </div>

                  </div>
                  <!-- /tile widget -->

                  <!-- tile body -->

                  <div class="tile-body color transparent-black rounded-bottom-corners">
                    <ul class="inline divided social-feed">

                      <li>
                        <h4>R$ <?=$k['valor']?></h4>
                        Valor
                      </li>

                      <? if(!is_null($k['pontos'])){ ?>

                      <li>
                        <h4><?=$k['pontos']?></h4>
                        Pontos
                      </li>

                      <? } ?>

                      <? if(!is_null($k['ganho'])){ ?>

                      <li>
                        <h4>R$ <?=$k['ganho']?></h4>
                        Ganho
                      </li>

                      <? } ?>

                      <li style="float: right; width: 37%;">
                        <button type="button" class="btn btn-success bt_addProduto" opt-idprod="<?=$k['id_produto']?>" opt-prod="<?=$k['produto']?>"><i class="fa fa-plus"></i> Adicionar ao pedido</button>
                      </li>

                    </ul>

                  </div>
                      <!-- /tile body -->

                </section>
                <!-- /tile -->
              </div>  

              <? } ?>

            </div>
                
          </div>
              <!-- /col 12 -->
              
        </div>
            <!-- /row -->

      </div>  
          <!-- /content container -->

      </div>
        <!-- Page content end -->

      </div>
      <!-- Make page fluid-->

    </div>
    <!-- Wrap all page content end -->

    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js?lang=css&amp;skin=sons-of-obsidian"></script>
    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap-dropdown-multilevel.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/mmenu/js/jquery.mmenu.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/sparkline/jquery.sparkline.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/nicescroll/jquery.nicescroll.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/animate-numbers/jquery.animateNumbers.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/blockui/jquery.blockUI.js')?>"></script>
    <script src="<?=Url::base('core/js/devem/minimal.js')?>"></script>

  </body>
</html>
      