<? $p = $this->pParametros(); ?>
<!DOCTYPE html>
<html>
  <head>
    <title>Devem Admin - Dvillagra</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <meta name="description" content="Devem Admin - Dvillagra" />

    <meta name="author" content="Dvillagra" />

    <link rel="shortcut icon" href="<?=Url::baseAdmin('view/img/favicon.ico')?>">

    <?php include('admin/include/scriptMenu.admin.php');?>

  </head>

  <body>

    <!-- @HEADER -->
      <?php include('admin/include/header.admin.php');?>
    <!-- @END HEADER -->

        <!-- Sub Nav End -->
        <div class="sub-nav hidden-sm hidden-xs">
          <ul>
            <li><a href="" class="heading">Extras</a></li>
            <li class="hidden-sm hidden-xs">
              <a href="edit-profile.html" class="selected">
                Edit profile
              </a>
            </li>
            <li class="hidden-sm hidden-xs">
              <a href="default.html">
                Default Page
              </a>
            </li>
            <li class="hidden-sm hidden-xs">
              <a href="invoice.html">
                Invoice
              </a>
            </li>
            <li class="hidden-sm hidden-xs">
              <a href="help.html">
                Help
              </a>
            </li>
          </ul>
          <div class="custom-search hidden-sm hidden-xs">
            <input type="text" class="search-query" placeholder="Search here ...">
            <i class="fa fa-search"></i>
          </div>
        </div>
        <!-- Sub Nav End -->

        <!-- Dashboard Wrapper Start -->
        <div class="dashboard-wrapper">
          
          <!-- Left Sidebar Start -->
          <div class="left-sidebar">
            
            <!-- Row Start -->
            <div class="row">
              <div class="col-lg-12 col-md-12">
                <div class="widget no-margin">
                  <div class="widget-header">
                    <div class="title">
                      Edit Profile
                    </div>
                    <span class="tools">
                      <i class="fa fa-cogs"></i>
                    </span>
                  </div>
                  <div class="widget-body">
                    <div class="row">
                      <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12">
                        <div class="thumbnail">
                          <img alt="300x200" src="img/profile.png">
                          <br>
                          <h4 class="center-align-text">UI Designer</h4>
                          <p class="center-align-text">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean porttitor a vulputate metus tristique vel orci quis sagittis.
                          </p>
                          <p class="btn-stack center-align-text">
                            <a href="javascript:;" class="btn btn-info">
                              <i class="fa fa-twitter"></i>
                            </a>
                            <a href="javascript:;" class="btn btn-primary">
                              <i class="fa fa-facebook"></i>
                            </a>
                            <a href="javascript:;" class="btn btn-danger">
                              <i class="fa fa-google-plus"></i>
                            </a>
                            <a href="javascript:;" class="btn btn-success">
                              <i class="fa fa-pinterest"></i>
                            </a>
                            <a href="javascript:;" class="btn btn-warning">
                              <i class="fa fa-youtube"></i>
                            </a>
                          </p>
                        </div>
                        <br>
                      </div>
                      <div class="col-lg-9 col-md-8 col-sm-12 col-xs-12">
                        <form class="form-horizontal">
                          <h5>
                            Login Information
                          </h5>
                          <hr>
                          <div class="form-group">
                            <label for="emailId" class="col-sm-3 control-label">Email ID</label>
                            <div class="col-sm-9">
                              <input type="email" class="form-control" id="emailId" placeholder="Email ID">
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="inputPassword" class="col-sm-3 control-label">Password</label>
                            <div class="col-sm-9">
                              <input type="password" class="form-control" id="inputPassword" placeholder="Password">
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="inputPassword1" class="col-sm-3 control-label">Confirm Password</label>
                            <div class="col-sm-9">
                              <input type="password" class="form-control" id="inputPassword1" placeholder="Confirm Password">
                            </div>
                          </div>
                          
                          <br />
                          <h5>
                            Personal Information
                          </h5>
                          <hr>
                          <div class="form-group">
                            <label for="userName" class="col-sm-3 control-label">Name</label>
                            <div class="col-sm-9">
                              <input type="email" class="form-control" id="userName" placeholder="Name">
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="location" class="col-sm-3 control-label">Location</label>
                            <div class="col-sm-9">
                              <input type="text" class="form-control" id="location" placeholder="Location">
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="webUrl" class="col-sm-3 control-label">Website Url</label>
                            <div class="col-sm-9">
                              <input type="url" class="form-control" id="webUrl" placeholder="Website Url">
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="webUrl" class="col-sm-3 control-label">About</label>
                            <div class="col-sm-9">
                              <textarea class="form-control" rows="5"></textarea>
                            </div>
                          </div>
                          <div class="form-actions">
                            <button type="submit" class="btn btn-info pull-right">
                              Save changes
                            </button>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- Row End -->

          </div>
          <!-- Left Sidebar End -->

          <!-- Right Sidebar Start -->
          <div class="right-sidebar">
            <div class="wrapper">
              <div class="list-group no-margin">
                <a href="javascript:;" class="list-group-item">
                  <span class="pull-right">
                    <i class="fa fa-facebook fa-3x text-facebook"></i>
                  </span>
                  <h4 class="list-group-item-heading">2,239</h4>
                  <p class="list-group-item-text">Shares</p>
                </a>
                <a href="javascript:;" class="list-group-item">
                  <span class="pull-right">
                    <i class="fa fa-twitter fa-3x text-twitter"></i>
                  </span>
                  <h4 class="list-group-item-heading">7,689</h4>
                  <p class="list-group-item-text">Tweets</p>
                </a>
                <a href="javascript:;" class="list-group-item">
                  <span class="pull-right">
                    <i class="fa fa-envelope fa-3x text-success"></i>
                  </span>
                  <h4 class="list-group-item-heading">1,532</h4>
                  <p class="list-group-item-text">Mails</p>      
                </a>
                <a href="javascript:;" class="list-group-item">
                  <span class="pull-right">
                    <i class="fa fa-user fa-3x text-warning"></i>
                  </span>
                  <h4 class="list-group-item-heading">8710</h4>
                  <p class="list-group-item-text">Users</p>      
                </a>
              </div>
            </div>
            
            <hr>
            
            <div class="wrapper">
              <ul class="month-income">
                <li>
                  <span class="icon-block blue-block">
                    <i class="fa fa-html5 fa-lg"></i>
                  </span>
                  <h5>
                    @srinubasava 
                    <small class="info-fade">
                      Developer
                    </small>
                  </h5>
                  <p>
                    10 minutes ago
                  </p>
                </li>
                <li>
                  <span class="icon-block orange-block">
                    <i class="fa fa-apple fa-lg"></i>
                  </span>
                  <h5>
                    @prempillai 
                    <small class="info-fade">
                      Sr. Developer
                    </small>
                  </h5>
                  <p>
                    28 minutes ago
                  </p>
                </li>
                <li>
                  <span class="icon-block green-block">
                    <i class="fa fa-github fa-lg"></i>
                  </span>
                  <h5>
                    @arjunurs 
                    <small class="info-fade">
                      Developer
                    </small>
                  </h5>
                  <p>
                    14 minutes ago
                  </p>
                </li>
                <li>
                  <span class="icon-block red-block">
                    <i class="fa fa-xing fa-lg"></i>
                  </span>
                  <h5>
                    @gajjugujju 
                    <small class="info-fade">
                      Team Leader
                    </small>
                  </h5>
                  <p>
                    28 minutes ago
                  </p>
                </li>
                <li>
                  <span class="icon-block yellow-block">
                    <i class="fa fa-css3 fa-lg"></i>
                  </span>
                  <h5>
                    @boomer 
                    <small class="info-fade">
                      Business
                    </small>
                  </h5>
                  <p>
                    28 minutes ago
                  </p>
                </li>
              </ul>
            </div>

          </div>
          <!-- Right Sidebar End -->

        </div>
        <!-- Dashboard Wrapper End -->

        <!-- @FOOTER -->
        <?php include('admin/include/footer.admin.php');?>
      <!-- @END FOOTER -->

      </div>
    </div>
    <!-- Main Container end -->

    <script src="<?=Url::baseAdmin('view/js/jquery.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/bootstrap.min.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/jquery.scrollUp.js')?>"></script>

    <!-- Custom JS -->
    <script src="<?=Url::baseAdmin('view/js/menu.js')?>"></script>
    
    <script type="text/javascript">
      //ScrollUp
      $(function () {
        $.scrollUp({
          scrollName: 'scrollUp', // Element ID
          topDistance: '300', // Distance from top before showing element (px)
          topSpeed: 300, // Speed back to top (ms)
          animation: 'fade', // Fade, slide, none
          animationInSpeed: 400, // Animation in speed (ms)
          animationOutSpeed: 400, // Animation out speed (ms)
          scrollText: 'Top', // Text for element
          activeOverlay: false, // Set CSS color to display scrollUp active point, e.g '#00FFFF'
        });
      });

      //Tooltip
      $('a').tooltip('hide');

      //Popover
      $('.popover-pop').popover('hide');

      //Dropdown
      $('.dropdown-toggle').dropdown();

    </script>

  </body>
</html>