<? $p = $this->pParametros(); ?>

<!DOCTYPE html>
<html>
  <head>

      <meta charset="utf-8">

      <?php include('core/include.tags.core.php');?>

      <?php require_once('core/include.scripts.core.php');?>

      <link rel="stylesheet" href="<?=Url::base('core/js/vendor/datatables/css/dataTables.bootstrap.css')?>" type="text/css" />
      <link rel="stylesheet" href="<?=Url::base('core/js/vendor/datatables/css/ColVis.css')?>" type="text/css" />
      <link rel="stylesheet" href="<?=Url::base('core/js/vendor/datatables/css/TableTools.css')?>" type="text/css" />

      <script  src="<?=Configuracoes::CheckFileCustomer('js/Cliente.class.js', true)?>" ></script>
    
  </head>

  <body class="bg-1">

    <!-- Preloader -->
    <div class="mask"><div id="loader"></div></div>
    <!--/Preloader -->

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Make page fluid -->
      <div class="row">

        <!-- @HEADER -->
          <?php include('core/include.header.core.php');?>
        <!-- @END HEADER -->
        
        
        <!-- Page content -->
        <div id="content" class="col-md-12">
          
          <!-- page header -->
          <div class="pageheader">
            
            <h2><i class="fa fa-star" style="line-height: 48px;padding-left: 0;"></i> Ranking</h2>
            
            <div class="breadcrumbs">

              <ol class="breadcrumb">

                <li>Você está em</li>
                <li><a>Rendimento</a></li>
                <li><a>Ranking</a></li>

              </ol>

            </div>

          </div>
          <!-- /page header -->
          
          <!-- content main container -->
          <div class="main">

            <!-- row -->
            <div class="row">

              <!-- col 12 -->
              <div class="col-md-12">
                
                <!-- /tile -->

                <!-- tile -->
                <section class="tile transparent">


                  <!-- tile header -->
                  <div class="tile-header transparent">

                    <h1>Posicionamento de Representantes </h1>

                    <div class="controls">

                      <a href="#" class="minimize"><i class="fa fa-chevron-down"></i></a>
                      <!--a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                      <a href="#" class="remove"><i class="fa fa-times"></i></a-->

                    </div>

                  </div>
                  <!-- /tile header -->

                  <!-- tile body -->
                  <div class="tile-body color transparent-black rounded-corners">
                    
                    <div class="table-responsive">
                      <table  class="table table-datatable table-custom" id="basicDataTable">
                        <thead>
                          <tr>
                            <th class="sort-alpha">Posição</th>
                            <th class="sort-alpha">Usuário</th>
                            <th class="sort-amount">Representante</th>
                            <th class="sort-numeric">Pontuação</th>
                            <th>Insignia</th>
                          </tr>
                        </thead>
                        <tbody>

                          <?
                            foreach ($p as $k) {
                          ?>

                          <tr class="odd gradeX">
                                  <td><?=$k['posicao']?></td>
                                  <td><?=$k['user_login']?></td>
                                  <td><?=$k['representante']?></td>
                                  <td class="text-center"><?=$k['pontuacao']?></td>
                                  <td class="text-center"><?=$k['insignia']?></td>
                          </tr>

                          <? 
                            }
                          ?>
                        </tbody>
                      </table>

                    </div>

                  </div>
                  <!-- /tile body -->
                
                </section>
                <!-- /tile -->

              </div>
              <!-- /col 12 -->

            </div>
            <!-- /row -->
          
          </div>
          <!-- /content container -->

        </div>
        <!-- Page content end -->

      </div>
      <!-- Make page fluid-->

    </div>
    <!-- Wrap all page content end -->

    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js?lang=css&amp;skin=sons-of-obsidian"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/jquery.dataTables.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/ColReorderWithResize.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/colvis/dataTables.colVis.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/tabletools/ZeroClipboard.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/tabletools/dataTables.tableTools.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/dataTables.bootstrap.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap-dropdown-multilevel.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/mmenu/js/jquery.mmenu.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/sparkline/jquery.sparkline.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/nicescroll/jquery.nicescroll.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/animate-numbers/jquery.animateNumbers.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/blockui/jquery.blockUI.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/tabdrop/bootstrap-tabdrop.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/summernote/summernote.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/chosen/chosen.jquery.min.js')?>"></script>
    <script src="<?=Url::base('core/js/devem/minimal.js')?>"></script>

    <script>

    // Add custom class to pagination div
      $.fn.dataTableExt.oStdClasses.sPaging = 'dataTables_paginate paging_bootstrap paging_custom';

      $('div.dataTables_filter input').addClass('form-control');
      $('div.dataTables_length select').addClass('form-control');

      /*************************************************/
      /**************** BASIC DATATABLE ****************/
      /*************************************************/

      /* Define two custom functions (asc and desc) for string sorting */
      jQuery.fn.dataTableExt.oSort['string-case-asc']  = function(x,y) {
          return ((x < y) ? -1 : ((x > y) ?  1 : 0));
      };
       
      jQuery.fn.dataTableExt.oSort['string-case-desc'] = function(x,y) {
          return ((x < y) ?  1 : ((x > y) ? -1 : 0));
      };

      /* Add a click handler to the rows - this could be used as a callback */
      $("#basicDataTable tbody tr").click( function( e ) {
        if ( $(this).hasClass('row_selected') ) {
          $(this).removeClass('row_selected');
        }
        else {
          oTable01.$('tr.row_selected').removeClass('row_selected');
          $(this).addClass('row_selected');
        }

        // FadeIn/Out delete rows button
        if ($('#basicDataTable tr.row_selected').length > 0) {
          $('#deleteRow').stop().fadeIn(300);
        } else {
          $('#deleteRow').stop().fadeOut(300);
        }
      });

      /* Build the DataTable with third column using our custom sort functions */
      var oTable01 = $('#basicDataTable').dataTable({
        "sDom":
          "R<'row'<'col-md-6'l><'col-md-6'f>r>"+
          "t"+
          "<'row'<'col-md-4 sm-center'i><'col-md-4'><'col-md-4 text-right sm-center'p>>",
        "oLanguage": {
          "sSearch": "",
          "oPaginate": {
                      "sNext": "Próximo",
                      "sPrevious": "Anterior"
                    },
          "sInfo": "Total de registros: _TOTAL_ (_START_ até _END_)",
          "sEmptyTable": "Você não possui nenhum cliente",
          "sLengthMenu": "_MENU_ por página"
        },
        "aaSorting": [ [0,'asc'], [1,'asc'] ],
        "aoColumns": [
          null,
          null,
          { "sType": 'string-case' },
          null,
          null
        ],
        "fnInitComplete": function(oSettings, json) { 
          $('.dataTables_filter input').attr("placeholder", "Buscar");
          if($("#basicDataTable_info").html() == 'Showing 0 to 0 of 0 entries')
            $("#basicDataTable_info").remove();

          $("#basicDataTable_length label select").css('color', '#666');
        }
      });

      // Append delete button to table
      var deleteRowLink = '<a href="#" id="deleteRow" class="btn btn-red btn-xs delete-row">Delete selected row</a>'
      $('#basicDataTable_wrapper').append(deleteRowLink);

      /* Add a click handler for the delete row */
      $('#deleteRow').click( function() {
        var anSelected = fnGetSelected(oTable01);
        if (anSelected.length !== 0 ) {
          oTable01.fnDeleteRow(anSelected[0]);
          $('#deleteRow').stop().fadeOut(300);
        }
      });

      /* Get the rows which are currently selected */
      function fnGetSelected(oTable01Local){
        return oTable01Local.$('tr.row_selected');
      };

    </script>

  </body>
</html>
      