<? $p = $this->pParametros(); ?>

<!DOCTYPE html>
<html>
  <head>

      <meta charset="utf-8">

      <?php include('core/include.tags.core.php');?>

      <?php require_once('core/include.scripts.core.php');?>

      <script  src="<?=Configuracoes::CheckFileCustomer('js/Relatorio.class.js', true)?>" ></script>
    
  </head>

  <body class="bg-1">

    <!-- Preloader -->
    <div class="mask"><div id="loader"></div></div>
    <!--/Preloader -->

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Make page fluid -->
      <div class="row">
        
        <!-- @HEADER -->
          <?php include('core/include.header.core.php');?>
        <!-- @END HEADER -->

        <!-- Page content -->
        <div id="content" class="col-md-12">
          
          <!-- page header -->
          <div class="pageheader">
            
            <h2><i class="fa fa-users" style="line-height: 48px;padding-left: 0;"></i> Relatórios</h2>
            
            <div class="breadcrumbs">

              <ol class="breadcrumb">

                <li>Você está em</li>
                <li><a>Relatórios</a></li>

              </ol>

            </div>

          </div>
          <!-- /page header -->
          
          <!-- content main container -->
          <div class="main">

            <!-- row -->
            <div class="row">

              <div class="col-md-6">

                 <!-- tile -->
                <section class="tile color transparent-black">

                  <!-- tile header -->
                  <div class="tile-header">

                    <h1>Novos Clientes</h1>

                    <div class="controls">

                      <a href="#" class="minimize"><i class="fa fa-chevron-down"></i></a>
                      <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                      <a href="#" class="remove"><i class="fa fa-times"></i></a>

                    </div>

                  </div>
                  <!-- /tile header -->

                  <!-- tile body -->
                  <div class="tile-body">
                    
                    <table id="line-chart" class="flot-chart" data-type="lines" data-width="100%" data-height="250px" data-font-color="rgba(255,255,255,.8)" data-tick-color="rgba(255,255,255,.3)" data-legend="hidden" data-tool-tip="show">
                      <thead>
                        <tr>
                          <th></th>
                          <th style="color : #cd97eb;">Ganho</th>
                        </tr>
                      </thead>
                      <tbody>

                        <tr>
                          <th>JAN</th>
                          <td>254</td>
                        </tr>

                        <tr>
                          <th>FEB</th>
                          <td>584</td>
                        </tr>

                      </tbody>
                    </table>

                  </div>
                  <!-- /tile body -->
                  
                </section>

              </div>

              <div class="col-md-6">

                <!-- tile -->
                <section class="tile color transparent-black">

                  <!-- tile header -->
                  <div class="tile-header">

                    <h1>Reputação dos clientes <strong>X</strong> Potencial de rendimentos</h1>

                    <div class="controls">

                      <a href="#" class="minimize"><i class="fa fa-chevron-down"></i></a>
                      <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>

                    </div>

                  </div>
                  <!-- /tile header -->

                  <!-- tile body -->
                  <div class="tile-body">

                    <div id="browser-usage" style="height: 230px;" class="morris-chart"></div>

                    <ul class="inline text-center chart-legend">

                      <li><span class="badge badge-outline" style="border-color: #1693A5"></span> Ótimo <small><span id="dd-otimo">0</span>%</small>,</li>
                      <li><span class="badge badge-outline" style="border-color: #ffc100"></span> Regular <small><span id="dd-regular">0</span>%</small>,</li>
                      <li><span class="badge badge-outline" style="border-color: #d9544f"></span> Ruim <small><span id="dd-ruim">0</span>%</small></li>

                    </ul>

                  </div>
                  <!-- /tile body --> 

                </section>
                <!-- /tile -->
                
              </div>

              <div class="col-md-12">

                <section class="tile color transparent-black">

                  <!-- tile header -->
                  <div class="tile-header">

                    <h1><strong>Pedidos</strong> X Status</h1>

                    <div class="controls">

                      <a class="minimize" href="#"><i class="fa fa-chevron-down"></i></a>
                      <a class="refresh" href="#"><i class="fa fa-refresh"></i></a>
                      <a class="remove" href="#"><i class="fa fa-times"></i></a>

                    </div>

                  </div>
                  <!-- /tile header -->

                  <!-- tile body -->
                  <div class="tile-body">
                    
                    <table id="stack-chart" class="flot-chart" data-type="bars" data-stack="true" data-tool-tip="show" data-width="100%" data-height="250px" data-font-color="rgba(255,255,255,.8)" data-legend="hidden" data-y-max="3500" data-tick-color="rgba(255,255,255,.3)">
                      <thead>
                        <tr>
                          <th></th>
                          <th style="color : #555;">Sales</th>
                          <th style="color : #FF0066;">Orders</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <th>JAN</th>
                          <td>254</td>
                          <td>125</td>
                        </tr>
                        <tr>
                          <th>FEB</th>
                          <td>584</td>
                          <td>345</td>
                        </tr>
                        <tr>
                          <th>MAR</th>
                          <td>85</td>
                          <td>120</td>
                        </tr>
                      </tbody>
                    </table>

                  </div>
                  <!-- /tile body -->
                  
                </section>

              </div>

            </div>
            <!-- /row -->
          
          </div>
          <!-- /content container -->

        </div>
        <!-- Page content end -->

      </div>
      <!-- Make page fluid-->

    </div>
    <!-- Wrap all page content end -->

    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap-dropdown-multilevel.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/mmenu/js/jquery.mmenu.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/sparkline/jquery.sparkline.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/nicescroll/jquery.nicescroll.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/animate-numbers/jquery.animateNumbers.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/blockui/jquery.blockUI.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/morris/morris.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/rickshaw/raphael-min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/tabdrop/bootstrap-tabdrop.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/summernote/summernote.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/chosen/chosen.jquery.min.js')?>"></script>
    <script src="<?=Url::base('core/js/devem/minimal.min.js')?>"></script>

    <script src="<?=Url::base('core/js/vendor/flot/jquery.flot.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/flot/jquery.flot.categories.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/flot/jquery.flot.pie.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/flot/jquery.flot.stack.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/graphtable/jquery.graphTable-0.3.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/flot/jquery.flot.tooltip.min.js')?>"></script>

  </body>
  
</html>
      