<? $p = $this->pParametros(); ?>
<!DOCTYPE html>
<html>
  <head>
    <title>Devem Admin - Dvillagra</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <meta name="description" content="Devem Admin - Dvillagra" />

    <meta name="author" content="Dvillagra" />

    <link rel="shortcut icon" href="<?=Url::baseAdmin('view/img/favicon.ico')?>">

    <?php include('admin/include/scriptMenu.admin.php');?>

  </head>

  <body>

    <!-- @HEADER -->
      <?php include('admin/include/header.admin.php');?>
    <!-- @END HEADER -->

        <!-- Sub Nav End -->
        <div class="sub-nav hidden-sm hidden-xs">
          <ul>
            <li><a href="" class="heading">Timeline</a></li>
          </ul>
          <div class="custom-search hidden-sm hidden-xs">
            <input type="text" class="search-query" placeholder="Buscar ...">
            <i class="fa fa-search"></i>
          </div>
        </div>
        <!-- Sub Nav End -->

        <!-- Dashboard Wrapper Start -->
        <div class="dashboard-wrapper">
          
          <!-- Left Sidebar Start -->
          <div class="left-sidebar">
            
            <!-- Row Start -->
            <div class="row">
              <div class="col-lg-12 col-md-12">
                <div class="widget">
                  <div class="widget-header">
                    <div class="title">
                      Timeline
                    </div>
                  </div>
                  <div class="widget-body">
                    <!-- Timeline starts -->
                    <div class="timeline">
                      <div class="timeline-row">
                        <div class="timeline-time">
                          6:44 PM<small>Feb 28</small>
                        </div>
                        <div class="timeline-icon">
                          <div class="danger-bg">
                            <i class="fa fa-pencil"></i>
                          </div>
                        </div>
                        <div class="panel timeline-content">
                          <div class="panel-body">
                            <h2 class="text-info">Heading</h2>
                            <p>
                              Simply dummy text of the printing and type setting industry lorem Ipsum.
                            </p>
                          </div>
                        </div>
                      </div>
                      <div class="timeline-row">
                        <div class="timeline-time">
                          3:54 PM<small>Feb 25</small>
                        </div>
                        <div class="timeline-icon">
                          <div class="warning-bg">
                            <i class="fa fa-quote-right"></i>
                          </div>
                        </div>
                        <div class="panel timeline-content">
                          <div class="panel-body">
                            <p>
                              Industry's standard orem Ipsum has been the dummy text ever since the 1500s.
                            </p>
                          </div>
                        </div>
                      </div>
                      <div class="timeline-row">
                        <div class="timeline-time">
                          3:00 PM<small>Feb 20</small>
                        </div>
                        <div class="timeline-icon">
                          <div class="success-bg">
                            <i class="fa fa-dollar"></i>
                          </div>
                        </div>
                        <div class="panel timeline-content">
                          <div class="panel-body">
                            <h2 class="text-info">Timeline Title</h2>
                            <div class="row">
                              <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                <img class="img-responsive" src="img/user8.jpg" alt="User" />
                              </div>
                              <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                <img class="img-responsive" src="img/user4.jpg" alt="User" />
                              </div>
                              <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                <img class="img-responsive" src="img/user5.jpg" alt="User" />
                              </div>
                              <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                <img class="img-responsive" src="img/user6.jpg" alt="User" />
                              </div>
                            </div>
                            <p>
                              Typesetting, remaining essentially unchanged it has survived not only five centuries, but also the leap into electronic t.
                            </p>
                          </div>
                        </div>
                      </div>
                      <div class="timeline-row">
                        <div class="timeline-time">
                          2:11 PM<small>Feb 12</small>
                        </div>
                        <div class="timeline-icon">
                          <div class="facebook-bg">
                            <i class="fa fa-facebook"></i>
                          </div>
                        </div>
                        <div class="panel timeline-content">
                          <div class="panel-body">
                            <h2 class="text-info">Facebook Post</h2>
                            <p>
                              <i class="fa fa-lg fa-quote-left"></i> The majority have suffered alteration in some form here are many variations of passages of Lorem Ipsum available. <i class="fa fa-lg fa-quote-right"></i>
                            </p>
                          </div>
                        </div>
                      </div>
                      <div class="timeline-row">
                        <div class="timeline-time">
                          7:35 PM<small>Jan 21</small>
                        </div>
                        <div class="timeline-icon">
                          <div class="success-bg">
                            <i class="fa fa-foursquare"></i>
                          </div>
                        </div>
                        <div class="panel timeline-content">
                          <div class="panel-body">
                            <h2 class="text-info">Timeline Post</h2>
                            <p>
                              Lorem ipsum velit ullamco anim pariatur proident eu deserunt laborum. Lorem ipsum ad in nostrud adipisicing cupidatat anim officia ad id cupidatat veniam quis elit ullamco.
                            </p>
                          </div>
                        </div>
                      </div>
                      <div class="timeline-row">
                        <div class="timeline-time">
                          8:00 PM<small>Jan 17</small>
                        </div>
                        <div class="timeline-icon">
                          <div class="warning-bg">
                            <i class="fa fa-user"></i>
                          </div>
                        </div>
                        <div class="panel timeline-content">
                          <div class="panel-body">
                            <p>Sed pretium, ligula sollicitudin laoreet viverra, tortor libero sodales leo, eget blandit nunc tortor eu nibh.</p>
                            <img class="img-responsive less-round" src="img/3.jpg" alt="User" />
                            <p>
                              Nullam mollis ut justo suspendisse potenti kqhduwqh klaebbs krwvacbve.
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- Timeline ends -->
                  </div>
                </div>
              </div>
            </div>
            <!-- Row End -->

          </div>
          <!-- Left Sidebar End -->

          <!-- Right Sidebar Start -->
          <div class="right-sidebar">
            
            <div class="wrapper">
              <div id="scrollbar">
                <div class="scrollbar">
                  <div class="track">
                    <div class="thumb">
                      <div class="end">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="viewport">
                  <div class="overview">
                    <div class="featured-articles-container">
                      <h5 class="heading">
                        Recent Articles
                      </h5>
                      <div class="articles">
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Hosting Made For WordPress
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Reinvent cutting-edge
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          partnerships models 24/7
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Eyeballs frictionless
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Empower deliver innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Mashups experiences plug
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Mashups experiences plug
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          B2B plug and play
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Need some interesting
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Mashups experiences plug
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          B2B plug and play
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Need some interesting
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Mashups experiences plug
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Need some interesting
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Mashups experiences plug
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          B2B plug and play
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Need some interesting
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Mashups experiences plug
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          B2B plug and play
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Need some interesting
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet">
                            &nbsp;
                          </span>
                          Mashups experiences plug
                        </a>
                      </div>
                      
                    </div>
                    
                  </div>
                </div>
              </div>
            </div>
            
            <hr class="hr-stylish-1">
            
            <div class="wrapper">
              <div id="scrollbar-two">
                <div class="scrollbar">
                  <div class="track">
                    <div class="thumb">
                      <div class="end">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="viewport">
                  <div class="overview">
                    <div class="featured-articles-container">
                      <h5 class="heading-blue">
                        Featured posts
                      </h5>
                      <div class="articles">
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Hosting Made For WordPress
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Reinvent cutting-edge
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          partnerships models 24/7
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Eyeballs frictionless
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Empower deliver innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Mashups experiences plug
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Need some interesting
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Mashups experiences plug
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          B2B plug and play
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Need some interesting
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Mashups experiences plug
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          B2B plug and play
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Need some interesting
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Portals technologies
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Collaborative innovate
                        </a>
                        <a href="#">
                          <span class="label-bullet-blue">
                            &nbsp;
                          </span>
                          Mashups experiences plug
                        </a>
                      </div>
                      
                    </div>
                    
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Right Sidebar End -->
        </div>
        <!-- Dashboard Wrapper End -->

        <!-- @FOOTER -->
        <?php include('admin/include/footer.admin.php');?>
      <!-- @END FOOTER -->

      </div>
    </div>
    <!-- Main Container end -->

    <script src="<?=Url::baseAdmin('view/js/jquery.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/bootstrap.min.js')?>"></script>
    <script src="<?=Url::baseAdmin('view/js/jquery.scrollUp.js')?>"></script>
    
    
    <!-- Tiny Scrollbar JS -->
    <script src="<?=Url::baseAdmin('view/js/tiny-scrollbar.js')?>"></script>
    
    <!-- Custom JS -->
    <script src="<?=Url::baseAdmin('view/js/menu.js')?>"></script>
    
    <script type="text/javascript">
      //ScrollUp
      $(function () {
        $.scrollUp({
          scrollName: 'scrollUp', // Element ID
          topDistance: '300', // Distance from top before showing element (px)
          topSpeed: 300, // Speed back to top (ms)
          animation: 'fade', // Fade, slide, none
          animationInSpeed: 400, // Animation in speed (ms)
          animationOutSpeed: 400, // Animation out speed (ms)
          scrollText: 'Top', // Text for element
          activeOverlay: false, // Set CSS color to display scrollUp active point, e.g '#00FFFF'
        });
      });

      //Tooltip
      $('a').tooltip('hide');
      $('i').tooltip('hide');

      //Tiny Scrollbar
      $('#scrollbar').tinyscrollbar();
      $('#scrollbar-two').tinyscrollbar();

    </script>

  </body>
</html>