<? 

  $p = $this->pParametros(); 

?>
<!DOCTYPE html>
<html>
  <head>

      <meta charset="utf-8">

      <?php include('core/include.tags.core.php');?>

      <?php require_once('admin/include/include.scripts.admin.php');?>
      
      <script src="<?=Url::baseAdmin('view/js/Usuario.class.js')?>?20150608"></script>  

  </head>

<body class="bg-1">

    <!-- Preloader -->
    <div class="mask"><div id="loader"></div></div>
    <!--/Preloader -->

    

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Make page fluid -->
      <div class="row">
        
        <!-- @HEADER -->
          <?php include('admin/include/include.header.admin.php');?>
        <!-- @END HEADER -->        
        
        <!-- Page content -->
        <div id="content" class="col-md-12">
          
          <!-- page header -->
          <div class="pageheader">
            
            <h2><i class="fa fa-user"></i> Usuário</h2>
            
            <div class="breadcrumbs">

              <ol class="breadcrumb">

                <li>Você está em </li>
                <li class="active">Usuário</li>

              </ol>

            </div>

          </div>
          <!-- /page header -->
          
          <!-- content main container -->
          <div class="main">

            <!-- cards -->
            <div class="row">

              <!-- col 4 -->
              <div class="col-md-4">
              

                <!-- tile -->
                <section class="tile transparent">

                  <!-- tile widget -->
                  <div class="tile-widget color transparent-white rounded-top-corners">
                    
                    <div class="user-card">
                      <h3><?=Session::get('auNome')?></h3>
                      <ul class="profile-controls inline">
                        <li class="avatar"><img src="<?=Url::imgApp(Session::get('auImagem'), false, true)?>" alt class="img-circle profile-photo"></li>
                      </ul>
                      <h5><?=constant('Nivel::N'.Session::get('auNivel'))?></h5>
                    </div>                       

                  </div>
                  <!-- /tile widget -->

                  <!-- tile body -->
                  <div class="tile-body color transparent-black textured rounded-bottom-corners">
                    <ul class="inline divided social-feed">
                      <li>
                        <h4><?=Session::get('auLogin')?></h4>
                        Login
                      </li>
                      <li>
                        <h4><?=Session::get('auEmail')?></h4>
                        Email
                      </li>
                      <li>
                        <h4><?=Utilitarios::dataDbtoBr(Session::get('auDataAtualizacao'))?></h4>
                        Ultima Atualização
                      </li>
                    </ul>
                  </div>
                  <!-- /tile body -->
                
                </section>
                <!-- /tile -->
              </div>

              <div class="col-md-8">

                <section class="tile color transparent-black">

                  <!-- tile header -->
                  <div class="tile-header">

                    <h1>Cadastro de novo Usuário </h1>

                  </div>
                  <!-- /tile header -->

                  <!-- tile body -->
                  <div class="tile-body">

                    <form id="form_cadastro">
                    
                      <div class="row">

                        <div class="form-group col-sm-3">

                          <label for="exampleInputEmail">Usuário</label>
                          <input type="text" placeholder="Nome de usuário" id="cd_nickname" name="cd_nickname" class="form-control form-devem-rec">

                        </div>

                        <div class="form-group col-sm-4">

                          <label for="exampleInputPassword1">Nome Completo</label>
                          <input type="text" placeholder="Nome" id="cd_nome" name="cd_nome" class="form-control form-devem-rec">
                        
                        </div>

                        <div class="form-group col-sm-5">

                          <label for="exampleInputPassword1">E-mail</label>
                          <input type="text" placeholder="E-mail" id="cd_email" name="cd_email" class="form-control form-devem-rec">
                        
                        </div>

                      </div>
                    
                      <div class="row">


                        <div class="form-group col-sm-4">
                        
                          <label for="exampleInputCity">Tipo de usuário</label>
                          <select class="chosen-select chosen-transparent form-control form-devem-rec" id="cd_nivel" name="cd_nivel">

                            <option value=""> - - - </option>
                            <option value="0">Administrador</option>
                            <option value="1">Gerente</option>
                            <option value="2">Operacional</option>

                          </select>
                        
                        </div>

                      </div>

                    </form>

                    <section class="log-in">
                     
                      <button class="btn btn-greensea" id="bt_cadastrar" >Cadastrar</button>
                    
                    </section>

                  </div>
                  <!-- /tile body -->
                
                </section>



              </div>

            </div>

            <div class="row">


                <!-- tile -->
                <section class="tile transparent">

                  <!-- tile header -->
                  <div class="tile-header transparent">
                    
                    <h1>Listagem de Usuários </h1>
                  
                  </div>
                  <!-- /tile header -->

                  <!-- tile body -->
                  <div class="tile-body rounded-corners">
                    
                    <div class="table-responsive">
                      
                      <table  class="table table-datatable table-custom" id="drillDownDataTable">

                        <thead>
                          <tr>
                            <th class="sort-alpha">ID</th>
                            <th class="sort-alpha">USUARIO</th>
                            <th class="sort-alpha">TIPO</th>
                            <th class="sort-alpha">NOME</th>
                            <th class="sort-alpha">EMAIL</th>
                            <th class="sort-alpha">DATA REGISTRO</th>
                          </tr>
                        </thead>

                        <tbody>
                        </tbody>
                      
                      </table>
                    
                    </div>

                  </div>
                  <!-- /tile body -->
                
                </section>
                <!-- /tile -->
            </div>
            <!-- /cards -->

          </div>
          <!-- /content container -->

        </div>
        <!-- Page content end -->

      </div>
      <!-- Make page fluid-->

    </div>
    <!-- Wrap all page content end -->

    <!-- Include all compiled plugins (below), or include individual files as needed -->

    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/bootstrap/bootstrap-dropdown-multilevel.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/mmenu/js/jquery.mmenu.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/sparkline/jquery.sparkline.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/nicescroll/jquery.nicescroll.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/animate-numbers/jquery.animateNumbers.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/blockui/jquery.blockUI.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/easypiechart/jquery.easypiechart.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/rickshaw/raphael-min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/rickshaw/d3.v2.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/rickshaw/rickshaw.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/morris/morris.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/tabdrop/bootstrap-tabdrop.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/summernote/summernote.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/chosen/chosen.jquery.min.js')?>"></script>
    <script src="<?=Url::base('core/js/devem/minimal.min.js')?>"></script>

    <script src="<?=Url::base('core/js/vendor/datatables/jquery.dataTables.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/ColReorderWithResize.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/colvis/dataTables.colVis.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/tabletools/ZeroClipboard.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/tabletools/dataTables.tableTools.min.js')?>"></script>
    <script src="<?=Url::base('core/js/vendor/datatables/dataTables.bootstrap.js')?>"></script>

    <script>
    $(function(){

      // Initialize card flip
      $('.card.hover').hover(function(){
        $(this).addClass('flip');
      },function(){
        $(this).removeClass('flip');
      });

      //generate actual pie charts
      $('.pie-chart').easyPieChart();

      // sortable table
      $('.table.table-sortable th.sortable').click(function() {
        var o = $(this).hasClass('sort-asc') ? 'sort-desc' : 'sort-asc';
        $('th.sortable').removeClass('sort-asc').removeClass('sort-desc');
        $(this).addClass(o);
      });

      // Initialize tabDrop
      $('.tabdrop').tabdrop({text: '<i class="fa fa-th-list"></i>'});

      //load wysiwyg editor
      $('#msg-box').summernote({
        toolbar: false,
        height: 161   //set editable area's height
      });

      

      $('#make-call a').click(function(){
        $(this).toggleClass('active');
      });

      $('.post-toolbar a').tooltip({
        placement: 'top',
        trigger: 'hover',
        html : true,
        container: 'body'
      }); 

      $('.task-controls .mark').click(function(){
        $(this).toggleClass('marked');
      });

      //accordion class active toggling
      $('.task-list .panel-heading .task-toggle').click(function() {

        var $previous = $( '.task-list .panel.active' );

        $previous.removeClass('active');
        $(this).parent().parent().stop().addClass('active');

        if($(this).parent().parent().hasClass('active')) {
          $previous.removeClass('active');
        }
      });

      //chosen select input
      $(".chosen-select").chosen({disable_search_threshold: 10});

      //initialize file upload button
      $('.btn-file :file').on('fileselect', function(event, numFiles, label) {
        
        var input = $(this).parents('.input-group').find(':text'),
            log = numFiles > 1 ? numFiles + ' files selected' : label;

            console.log(log);
        
        if( input.length ) {
          input.val(log);
        } else {
          if( log ) alert(log);
        }      
      });
      
    })
      
    </script>
  </body>
</html>
